/**
 * GENERATED by scripts/generate-page-dates.mjs. Do not edit by hand.
 *
 * published = first commit that added the page's source
 * updated   = most recent commit that touched it
 *
 * Neither is a "last checked" date; git cannot see a person re-reading a
 * vendor's page. See the generator's header for why these are not props.
 */
export type PageDates = { published: string; updated: string };

export const PAGE_DATES: Record<string, PageDates> = {
  "/about": {
    "published": "2025-11-22",
    "updated": "2026-08-25"
  },
  "/activecampaign": {
    "published": "2026-07-11",
    "updated": "2026-08-21"
  },
  "/admin/leads": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/affiliate-earnings-calculator": {
    "published": "2026-07-07",
    "updated": "2026-08-21"
  },
  "/affiliate-partnerships": {
    "published": "2026-02-04",
    "updated": "2026-02-24"
  },
  "/affiliate-programs-australia": {
    "published": "2026-07-05",
    "updated": "2026-08-25"
  },
  "/affiliate-software-australia": {
    "published": "2026-08-21",
    "updated": "2026-08-28"
  },
  "/ai-sales-tools-quiz": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/aisdr": {
    "published": "2026-07-06",
    "updated": "2026-08-21"
  },
  "/alidrop": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/analytics": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/anker-solix": {
    "published": "2026-08-25",
    "updated": "2026-08-26"
  },
  "/api-guide": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/apollo-energy-group": {
    "published": "2026-07-26",
    "updated": "2026-08-26"
  },
  "/apollo-energy-group-eoi": {
    "published": "2026-07-28",
    "updated": "2026-08-27"
  },
  "/apollo-energy-review": {
    "published": "2026-07-15",
    "updated": "2026-08-27"
  },
  "/auth/reset-password": {
    "published": "2025-12-11",
    "updated": "2026-08-27"
  },
  "/beautifulai": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/beehiiv": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/best-ai-sales-tools": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/best-crm-small-business-australia": {
    "published": "2026-07-24",
    "updated": "2026-08-21"
  },
  "/best-hair-loss-treatment-australia": {
    "published": "2026-06-29",
    "updated": "2026-08-31"
  },
  "/best-home-battery-australia": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/best-newsletter-platform": {
    "published": "2026-06-29",
    "updated": "2026-07-20"
  },
  "/best-pet-insurance-australia": {
    "published": "2026-08-17",
    "updated": "2026-08-31"
  },
  "/best-website-builder": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/best-weight-loss-telehealth-australia": {
    "published": "2026-06-29",
    "updated": "2026-09-03"
  },
  "/blinq": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/brevo": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/business-line-of-credit-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/business-loan-calculator": {
    "published": "2026-07-21",
    "updated": "2026-07-23"
  },
  "/business-loan-eligibility-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/business-loans": {
    "published": "2026-07-21",
    "updated": "2026-08-03"
  },
  "/business-loans-bad-credit-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/business-loans-hospitality-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/business-loans-sole-traders-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/business-software": {
    "published": "2026-07-10",
    "updated": "2026-09-03"
  },
  "/butternut": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/calendly": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/capsule": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/carrd": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/carrd-vs-butternut": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/carrd-vs-durable": {
    "published": "2026-06-30",
    "updated": "2026-07-16"
  },
  "/case-studies": {
    "published": "2025-12-07",
    "updated": "2026-07-30"
  },
  "/cheapest-weight-loss-telehealth-australia": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/cloudtalk": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/coming-soon": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/contact": {
    "published": "2025-11-25",
    "updated": "2026-08-25"
  },
  "/dashboard-test": {
    "published": "2026-01-13",
    "updated": "2026-01-13"
  },
  "/data": {
    "published": "2026-08-26",
    "updated": "2026-08-27"
  },
  "/deals": {
    "published": "2026-07-27",
    "updated": "2026-08-28"
  },
  "/dense": {
    "published": "2026-06-29",
    "updated": "2026-08-26"
  },
  "/dext": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/disclaimer": {
    "published": "2026-08-25",
    "updated": "2026-08-25"
  },
  "/durable-vs-butternut": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/durableai": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/early-signs-of-hair-loss-australia": {
    "published": "2026-08-07",
    "updated": "2026-08-07"
  },
  "/ecoflow": {
    "published": "2026-08-25",
    "updated": "2026-08-26"
  },
  "/ecoflow-vs-anker-solix": {
    "published": "2026-08-25",
    "updated": "2026-08-25"
  },
  "/elevenlabs": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/employmenthero": {
    "published": "2026-07-06",
    "updated": "2026-08-21"
  },
  "/equipment-finance-instant-asset-write-off": {
    "published": "2026-07-21",
    "updated": "2026-08-27"
  },
  "/faq": {
    "published": "2025-12-10",
    "updated": "2026-08-25"
  },
  "/fast-business-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/flexiquiz": {
    "published": "2026-07-11",
    "updated": "2026-08-21"
  },
  "/for-business": {
    "published": "2026-07-03",
    "updated": "2026-08-25"
  },
  "/fullenrich": {
    "published": "2026-07-07",
    "updated": "2026-08-21"
  },
  "/go-live": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/gohighlevel": {
    "published": "2026-07-06",
    "updated": "2026-08-21"
  },
  "/gtm": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/guides": {
    "published": "2026-06-29",
    "updated": "2026-09-04"
  },
  "/hair-loss": {
    "published": "2026-07-03",
    "updated": "2026-08-27"
  },
  "/hair-loss-quiz": {
    "published": "2026-07-08",
    "updated": "2026-08-26"
  },
  "/hair-loss-treatment-cost-australia": {
    "published": "2026-07-17",
    "updated": "2026-08-27"
  },
  "/hellobar": {
    "published": "2026-07-11",
    "updated": "2026-08-21"
  },
  "/high-paying-affiliate-programs": {
    "published": "2026-07-05",
    "updated": "2026-08-25"
  },
  "/home-battery-blackout-backup-australia": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/home-battery-cost-australia": {
    "published": "2026-07-17",
    "updated": "2026-08-26"
  },
  "/home-battery-installer-nsw": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/home-battery-installer-sydney": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/home-battery-payback-calculator": {
    "published": "2026-07-20",
    "updated": "2026-08-26"
  },
  "/home-battery-rebate-australia": {
    "published": "2026-07-15",
    "updated": "2026-08-27"
  },
  "/home-battery-rebate-by-state-australia": {
    "published": "2026-07-28",
    "updated": "2026-08-26"
  },
  "/how-to-get-a-business-loan-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/how-to-start-affiliate-marketing-australia": {
    "published": "2026-07-05",
    "updated": "2026-08-27"
  },
  "/how-to-stop-hair-loss-australia": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/how-we-make-money": {
    "published": "2026-07-21",
    "updated": "2026-08-22"
  },
  "/hubspot": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/instapage": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/is-a-home-battery-worth-it-australia": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/juniper": {
    "published": "2026-07-29",
    "updated": "2026-08-27"
  },
  "/keap": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/klaviyo": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/knose": {
    "published": "2026-08-04",
    "updated": "2026-08-28"
  },
  "/knose-vs-petsonme": {
    "published": "2026-08-17",
    "updated": "2026-08-28"
  },
  "/krispcall": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/landingi": {
    "published": "2026-07-13",
    "updated": "2026-08-21"
  },
  "/lead-hacking": {
    "published": "2025-12-22",
    "updated": "2026-07-30"
  },
  "/leadpages": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/lindy": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/linkedin-growth/business": {
    "published": "2026-01-03",
    "updated": "2026-06-29"
  },
  "/linkedin-growth/influencer": {
    "published": "2026-01-03",
    "updated": "2026-07-09"
  },
  "/linkedin-growth": {
    "published": "2026-01-03",
    "updated": "2026-06-29"
  },
  "/linkedin-influencer/business": {
    "published": "2025-12-31",
    "updated": "2026-06-29"
  },
  "/linkedin-influencer/influencer": {
    "published": "2025-12-31",
    "updated": "2026-07-09"
  },
  "/linkedin-influencer": {
    "published": "2025-12-31",
    "updated": "2026-06-29"
  },
  "/login": {
    "published": "2025-11-22",
    "updated": "2026-02-24"
  },
  "/longevity/diagnostics/biological-age-testing-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/diagnostics/cgm-for-non-diabetics-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/diagnostics/everlab-vs-prenuvo-vs-i-screen-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/diagnostics/health-screening-quiz": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/longevity/diagnostics": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/diagnostics/whole-body-mri-australia-cost": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/longevity/recovery/contrast-therapy-what-the-evidence-says": {
    "published": "2026-08-20",
    "updated": "2026-08-28"
  },
  "/longevity/recovery/home-sauna-cost-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/longevity/recovery/ice-bath-comparison-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/recovery/ice-bath-running-costs-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-24"
  },
  "/longevity/recovery/infrared-vs-traditional-sauna-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/recovery": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/longevity/recovery/recovery-setup-quiz": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/longevity/supplements/longevity-supplements-evidence-review": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/low-doc-business-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/mailchimp": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/make": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/mens-health/erectile-dysfunction-treatment-cost-australia": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/is-telehealth-or-a-gp-cheaper-for-mens-health": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/mens-health-quiz": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/online-doctor-medical-certificate-australia": {
    "published": "2026-09-04",
    "updated": "2026-09-04"
  },
  "/mens-health/online-mens-health-clinics-compared": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/online-prescription-australia": {
    "published": "2026-09-04",
    "updated": "2026-09-04"
  },
  "/mens-health": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/premature-ejaculation-treatment-options-australia": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health/sexual-wellness-products": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/mens-health-telehealth-australia": {
    "published": "2026-07-02",
    "updated": "2026-08-28"
  },
  "/meta-ads": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/midoc": {
    "published": "2026-09-04",
    "updated": "2026-09-04"
  },
  "/mosh-review": {
    "published": "2026-08-07",
    "updated": "2026-08-28"
  },
  "/mosh-vs-dense": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/mosh-vs-pilot": {
    "published": "2026-07-06",
    "updated": "2026-09-03"
  },
  "/moshhair": {
    "published": "2026-06-29",
    "updated": "2026-08-27"
  },
  "/moshy": {
    "published": "2026-06-29",
    "updated": "2026-08-26"
  },
  "/moshy-alternatives": {
    "published": "2026-07-02",
    "updated": "2026-08-28"
  },
  "/moshy-eligibility": {
    "published": "2026-07-02",
    "updated": "2026-08-28"
  },
  "/moshy-review": {
    "published": "2026-07-02",
    "updated": "2026-08-31"
  },
  "/moshy-vs-gp": {
    "published": "2026-07-02",
    "updated": "2026-08-28"
  },
  "/moshy-vs-juniper": {
    "published": "2026-06-30",
    "updated": "2026-08-28"
  },
  "/moshy-vs-pilot": {
    "published": "2026-07-06",
    "updated": "2026-08-28"
  },
  "/newsletter-platform-quiz": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/nsw-home-battery-rebate-2026": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/nutshell": {
    "published": "2026-07-10",
    "updated": "2026-08-21"
  },
  "/online-hair-loss-treatment-australia": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/online-weight-loss-doctor-australia": {
    "published": "2026-07-05",
    "updated": "2026-08-28"
  },
  "/online-weight-loss-programs-australia": {
    "published": "2026-07-02",
    "updated": "2026-08-28"
  },
  "/outgrow": {
    "published": "2026-07-11",
    "updated": "2026-08-21"
  },
  "/": {
    "published": "2025-11-22",
    "updated": "2026-09-03"
  },
  "/pandadoc": {
    "published": "2026-07-14",
    "updated": "2026-08-21"
  },
  "/partner-with-refer-labs": {
    "published": "2026-08-25",
    "updated": "2026-08-25"
  },
  "/payment/cancel": {
    "published": "2025-12-18",
    "updated": "2026-08-27"
  },
  "/payment/success": {
    "published": "2025-12-18",
    "updated": "2026-08-27"
  },
  "/pet-insurance": {
    "published": "2026-08-04",
    "updated": "2026-08-27"
  },
  "/petsonme": {
    "published": "2026-08-17",
    "updated": "2026-08-28"
  },
  "/pipedrive": {
    "published": "2026-07-11",
    "updated": "2026-08-21"
  },
  "/playbooks": {
    "published": "2026-02-24",
    "updated": "2026-08-25"
  },
  "/portable-power-station-australia": {
    "published": "2026-08-25",
    "updated": "2026-08-25"
  },
  "/portable-vs-installed-home-battery-australia": {
    "published": "2026-08-25",
    "updated": "2026-08-25"
  },
  "/privacy": {
    "published": "2025-11-25",
    "updated": "2026-08-25"
  },
  "/r/ambassador-join": {
    "published": "2025-12-03",
    "updated": "2026-01-18"
  },
  "/r/referral": {
    "published": "2025-11-27",
    "updated": "2026-01-18"
  },
  "/receding-hairline-treatment-australia": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/recurring-affiliate-programs": {
    "published": "2026-07-05",
    "updated": "2026-08-25"
  },
  "/referral-partnerships": {
    "published": "2026-01-16",
    "updated": "2026-07-30"
  },
  "/referred": {
    "published": "2025-12-29",
    "updated": "2026-07-16"
  },
  "/replyio": {
    "published": "2026-07-07",
    "updated": "2026-08-21"
  },
  "/roi-calculator": {
    "published": "2025-12-07",
    "updated": "2026-08-25"
  },
  "/search": {
    "published": "2026-08-03",
    "updated": "2026-08-03"
  },
  "/secured-vs-unsecured-business-loans": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/security": {
    "published": "2025-11-22",
    "updated": "2026-07-16"
  },
  "/servicem8": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/services/accountants": {
    "published": "2026-01-12",
    "updated": "2026-06-29"
  },
  "/services/affiliate-distribution": {
    "published": "2026-06-29",
    "updated": "2026-08-31"
  },
  "/services/apac-expansion": {
    "published": "2026-06-29",
    "updated": "2026-08-31"
  },
  "/services/consultants-coaches": {
    "published": "2026-01-12",
    "updated": "2026-06-29"
  },
  "/services/financial-advisors": {
    "published": "2026-01-12",
    "updated": "2026-06-29"
  },
  "/services/influencer-activation": {
    "published": "2026-06-29",
    "updated": "2026-08-25"
  },
  "/services/insurance-brokers": {
    "published": "2026-01-12",
    "updated": "2026-06-29"
  },
  "/services": {
    "published": "2026-02-10",
    "updated": "2026-07-16"
  },
  "/services/partner-activation": {
    "published": "2026-06-29",
    "updated": "2026-08-25"
  },
  "/services/product-distribution": {
    "published": "2026-06-29",
    "updated": "2026-08-25"
  },
  "/services/recruiters-staffing": {
    "published": "2026-01-12",
    "updated": "2026-06-29"
  },
  "/services/referral-programs": {
    "published": "2026-06-29",
    "updated": "2026-08-31"
  },
  "/shopify/checkout-extensibility": {
    "published": "2025-12-28",
    "updated": "2026-07-16"
  },
  "/shopify": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/skin-and-beauty/acne-treatment-options-and-costs-australia": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/anti-ageing-treatments-what-they-cost": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/best-value-skincare-australia-cost-per-use": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/foreo-luna-vs-ufo": {
    "published": "2026-09-04",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/led-face-mask-comparison-australia": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/natural-skincare-australia": {
    "published": "2026-09-04",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/retinol-vs-prescription-strength-australia": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/skin-and-beauty/skincare-quiz": {
    "published": "2026-08-20",
    "updated": "2026-09-04"
  },
  "/sleep/cpap-machine-costs-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/sleep/do-i-have-sleep-apnoea": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/sleep/home-sleep-test-australia-cost": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/sleep/how-much-does-good-sleep-cost": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/sleep/mattress-comparison-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/sleep": {
    "published": "2026-08-20",
    "updated": "2026-08-21"
  },
  "/sleep/sleep-tracker-comparison-australia": {
    "published": "2026-08-20",
    "updated": "2026-08-20"
  },
  "/small-business-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/solar-and-battery-package-australia": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/solar-and-energy": {
    "published": "2026-08-25",
    "updated": "2026-08-26"
  },
  "/square": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/squarespace": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/startup-business-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/status": {
    "published": "2025-12-28",
    "updated": "2026-08-24"
  },
  "/stripe": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/superfiliate": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/survicate": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/swipepages": {
    "published": "2026-06-29",
    "updated": "2026-08-21"
  },
  "/terms": {
    "published": "2025-11-25",
    "updated": "2026-08-25"
  },
  "/tesla-powerwall-alternatives-australia": {
    "published": "2026-07-24",
    "updated": "2026-07-24"
  },
  "/trainual": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/true-cost-of-business-loans-australia": {
    "published": "2026-07-22",
    "updated": "2026-08-27"
  },
  "/unbounce": {
    "published": "2026-08-21",
    "updated": "2026-08-21"
  },
  "/unsecured-business-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/virtual-power-plant-australia": {
    "published": "2026-07-28",
    "updated": "2026-08-26"
  },
  "/webflow": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/website-builder-quiz": {
    "published": "2026-07-08",
    "updated": "2026-08-21"
  },
  "/weight-loss": {
    "published": "2026-07-03",
    "updated": "2026-08-28"
  },
  "/weight-loss-cost-calculator": {
    "published": "2026-07-07",
    "updated": "2026-08-26"
  },
  "/weight-loss-guide": {
    "published": "2026-08-12",
    "updated": "2026-08-25"
  },
  "/weight-loss-quiz": {
    "published": "2026-07-08",
    "updated": "2026-08-26"
  },
  "/weight-loss-telehealth-cost-australia": {
    "published": "2026-07-05",
    "updated": "2026-08-28"
  },
  "/weight-loss-telehealth-men-australia": {
    "published": "2026-07-02",
    "updated": "2026-08-26"
  },
  "/weight-loss-telehealth-women-australia": {
    "published": "2026-07-24",
    "updated": "2026-08-28"
  },
  "/weight-loss-treatment-eligibility-australia": {
    "published": "2026-08-07",
    "updated": "2026-08-26"
  },
  "/what-a-business-loan-actually-costs": {
    "published": "2026-07-21",
    "updated": "2026-08-27"
  },
  "/what-pet-insurance-covers-australia": {
    "published": "2026-08-04",
    "updated": "2026-08-27"
  },
  "/what-size-home-battery-do-i-need-australia": {
    "published": "2026-07-22",
    "updated": "2026-07-22"
  },
  "/who-its-for/access-to-capital": {
    "published": "2026-02-24",
    "updated": "2026-02-24"
  },
  "/who-its-for/financial-tools": {
    "published": "2026-02-24",
    "updated": "2026-02-24"
  },
  "/who-its-for/global-investments": {
    "published": "2026-02-24",
    "updated": "2026-02-24"
  },
  "/who-its-for/niche-opportunities": {
    "published": "2026-02-24",
    "updated": "2026-06-29"
  },
  "/who-its-for": {
    "published": "2026-02-10",
    "updated": "2026-07-30"
  },
  "/who-underwrites-pet-insurance-australia": {
    "published": "2026-08-23",
    "updated": "2026-08-27"
  },
  "/wing-assistant": {
    "published": "2026-07-09",
    "updated": "2026-08-21"
  },
  "/wix": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  },
  "/wordpress": {
    "published": "2025-12-28",
    "updated": "2026-08-19"
  },
  "/working-capital-loans-australia": {
    "published": "2026-07-21",
    "updated": "2026-07-21"
  },
  "/zapier": {
    "published": "2025-12-28",
    "updated": "2026-08-28"
  }
};

export function pageDates(route: string): PageDates | undefined {
  return PAGE_DATES[route.replace(/\/$/, "") || "/"];
}
