import { Metadata } from "next";

export interface SEOConfig {
  title: string;
  description: string;
  keywords?: string[];
  image?: string;
  url?: string;
  type?: "website" | "article";
  noIndex?: boolean;
}

const SITE_NAME = "Refer Labs";
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://referlabs.com.au";
const TWITTER_HANDLE = "@referlabs";

/** Per-page, branded Open Graph card generated by /og from the page title. */
function dynamicOgImage(title: string): string {
  return `${SITE_URL}/og?title=${encodeURIComponent(title)}`;
}

/**
 * Generate comprehensive metadata for SEO, Open Graph, and Twitter Cards
 */
export function generateMetadata(config: SEOConfig): Metadata {
  const {
    title,
    description,
    keywords = [],
    image,
    url,
    type = "website",
    noIndex = false,
  } = config;

  const fullTitle = title.includes(SITE_NAME) ? title : `${title} | ${SITE_NAME}`;
  const canonicalUrl = url || SITE_URL;
  // Each page gets a unique, branded OG card built from its title unless an
  // explicit image is supplied — lifts social/SERP click-through site-wide.
  const ogImage = image || dynamicOgImage(title);

  return {
    metadataBase: new URL(SITE_URL),
    title: fullTitle,
    description,
    keywords: keywords.length > 0 ? keywords.join(", ") : undefined,

    // Robots
    robots: noIndex
      ? {
          index: false,
          follow: false,
        }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        },

    // Open Graph
    openGraph: {
      title: fullTitle,
      description,
      url: canonicalUrl,
      siteName: SITE_NAME,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      locale: "en_AU",
      type,
    },

    // Twitter Card
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [ogImage],
      creator: TWITTER_HANDLE,
      site: TWITTER_HANDLE,
    },

    // Additional meta tags
    alternates: {
      canonical: canonicalUrl,
    },

    // Verification tags
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    },

    // App-specific metadata
    applicationName: SITE_NAME,

    // Referrer policy
    referrer: "origin-when-cross-origin",

    // Category
    category: "Business Services",

    // Authors
    authors: [{ name: SITE_NAME }],

    // Creator
    creator: SITE_NAME,

    // Publisher
    publisher: SITE_NAME,

    // Format detection
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },

    // Icons
    icons: {
      icon: "/logo.svg",
      apple: "/logo.svg",
    },

    // Manifest
    manifest: "/manifest.json",
  };
}

/**
 * Pre-configured SEO configs for common pages
 */
export const seoConfig = {
  home: {
    title: "Referral Growth Blueprint — $799 AUD | Refer Labs",
    description:
      "250+ researched affiliate programs, a personalised strategy brief, SEO page concepts and distribution playbooks. Delivered in 48 hours. $799 AUD.",
    url: SITE_URL,
    keywords: [
      "referral blueprint",
      "affiliate program database australia",
      "best affiliate programs australia 2026",
      "how to start affiliate marketing australia",
      "referral system for business",
      "referral marketing australia",
      "affiliate marketing blueprint",
      "referral growth blueprint",
      "affiliate income blueprint",
      "passive income affiliate programs australia",
      "referral program setup",
      "affiliate marketing side hustle australia",
    ],
  },

  pricing: {
    title: "Pricing - Market Entry Engagement Models",
    description:
      "Choose the right engagement model for your APAC expansion. Retainer + commission pricing aligned to your growth stage. 90-day pilot structure.",
    url: `${SITE_URL}/pricing`,
    keywords: [
      "market entry pricing",
      "GTM services pricing",
      "expansion engagement cost",
      "partnership services pricing",
      "outsourced sales pricing",
    ],
  },

  howItWorks: {
    title: "How It Works — Refer Labs Growth & Distribution Engine",
    description:
      "See how Refer Labs builds and activates your growth engine — referral programs, affiliate distribution, influencer channels, APAC expansion, and digital products end to end.",
    url: `${SITE_URL}/how-it-works`,
    keywords: [
      "how referral programs work",
      "affiliate distribution process",
      "growth engine setup",
      "distribution channel activation",
      "referral marketing process",
    ],
  },

  services: {
    title: "Services — Five Growth Engines | Refer Labs",
    description:
      "Five growth engines: Referral Program Launch, Elite Affiliate Distribution, Influencer & Network Activation, APAC Market Expansion, and Product Creation & Distribution.",
    url: `${SITE_URL}/services`,
    keywords: [
      "referral program launch",
      "affiliate distribution service",
      "influencer activation agency",
      "APAC market expansion",
      "product distribution service",
      "growth engine agency",
    ],
  },

  whoItsFor: {
    title: "Who It's For — B2B & B2C Businesses Ready to Scale | Refer Labs",
    description:
      "Refer Labs works with SMBs, eCommerce brands, SaaS companies, and global operators who want to build referral programs, activate distribution channels, and scale through structured growth.",
    url: `${SITE_URL}/who-its-for`,
    keywords: [
      "referral program for SMB",
      "affiliate channel for ecommerce",
      "B2B distribution partner",
      "growth partner for SaaS",
      "who is refer labs for",
    ],
  },

  caseStudies: {
    title: "Playbooks — Growth & Distribution Examples | Refer Labs",
    description:
      "Example playbooks showing how we launch referral programs, activate affiliate and influencer channels, distribute digital products, and expand into APAC.",
    url: `${SITE_URL}/case-studies`,
    keywords: [
      "referral program examples",
      "affiliate distribution playbook",
      "growth engine examples",
      "distribution channel playbook",
    ],
  },

  about: {
    title: "About Refer Labs — Growth & Distribution Engine",
    description:
      "Refer Labs is a growth and distribution engine. We build referral programs, activate affiliate and influencer channels, expand businesses into APAC, and create distribution-driven products.",
    url: `${SITE_URL}/about`,
    keywords: [
      "about refer labs",
      "growth distribution agency",
      "referral marketing partner",
      "affiliate distribution agency Australia",
    ],
  },

  contact: {
    title: "Contact Refer Labs — Partner With Us",
    description:
      "Get in touch with Refer Labs. Book a call to discuss referral programs, affiliate distribution, influencer activation, APAC expansion, or product distribution.",
    url: `${SITE_URL}/contact`,
    keywords: [
      "contact refer labs",
      "book a call refer labs",
      "referral program consultation",
      "affiliate distribution enquiry",
    ],
  },

  faq: {
    title: "FAQ — Refer Labs Growth & Distribution Services",
    description:
      "Find answers to common questions about our referral programs, affiliate distribution, influencer activation, APAC expansion, and product distribution services.",
    url: `${SITE_URL}/faq`,
    keywords: [
      "refer labs FAQ",
      "referral program questions",
      "affiliate distribution FAQ",
      "growth services questions",
    ],
  },

  application: {
    title: "Apply to Work With Refer Labs",
    description:
      "Submit your application to work with Refer Labs. Tell us about your business, growth goals, and which services you need. We review every application and respond within 1-2 business days.",
    url: `${SITE_URL}/application`,
    keywords: [
      "apply refer labs",
      "referral program application",
      "work with refer labs",
      "growth partner application",
    ],
  },

  security: {
    title: "Security - Enterprise-grade data protection",
    description:
      "Learn about our security practices, data protection, and how we keep your business data safe and private.",
    url: `${SITE_URL}/security`,
    keywords: [
      "data security",
      "data protection",
      "enterprise security",
    ],
  },

  privacy: {
    title: "Privacy Policy - How we protect your data",
    description:
      "Read our privacy policy to understand how Refer Labs collects, uses, and protects your personal information.",
    url: `${SITE_URL}/privacy`,
    keywords: ["privacy policy", "data privacy", "data protection"],
  },

  terms: {
    title: "Terms of Service - Legal terms and conditions",
    description:
      "Read the terms of service for using Refer Labs, including user rights, responsibilities, and legal agreements.",
    url: `${SITE_URL}/terms`,
    keywords: ["terms of service", "legal terms", "user agreement"],
  },

  // Service landing pages
  referralPrograms: {
    title: "Referral Program Launch & Distribution AU | Refer Labs",
    description:
      "We design, launch, and actively distribute referral programs for B2B and B2C businesses. Incentive design, tracking, channel activation. Fully managed.",
    url: `${SITE_URL}/services/referral-programs`,
    keywords: [
      "referral program launch service",
      "referral program design",
      "referral program consultant australia",
      "how to launch a referral program",
      "referral marketing agency australia",
      "referral program setup service",
      "word of mouth marketing strategy",
      "referral program for saas",
      "referral program for ecommerce",
      "referral program management australia",
      "referral channel growth",
      "referral program incentive design",
      "referral tracking setup",
      "referral marketing program australia",
      "build a referral program",
      "customer referral program",
      "referral program strategy",
      "referral program distribution strategy",
      "referral growth service",
      "referral program optimisation",
    ],
  },

  affiliateDistribution: {
    title: "Affiliate Program Distribution Service | Refer Labs",
    description:
      "We distribute your affiliate offer into high-intent communities with an in-house team. Sector-exclusive representation. Source-level attribution tracking.",
    url: `${SITE_URL}/services/affiliate-distribution`,
    keywords: [
      "affiliate program management service",
      "affiliate distribution service",
      "affiliate marketing agency australia",
      "managed affiliate program",
      "outsource affiliate program management",
      "affiliate program distribution",
      "affiliate marketing management company",
      "affiliate program placement service",
      "affiliate community distribution",
      "grow affiliate program australia",
      "affiliate channel management",
      "b2b affiliate program distribution",
      "affiliate program launch and distribution",
      "affiliate distribution agency",
      "niche affiliate marketing placement",
      "reddit affiliate distribution",
      "affiliate program activation service",
      "affiliate program growth strategy",
      "affiliate marketing distribution channels",
      "affiliate program management australia",
    ],
  },

  influencerActivation: {
    title: "Partner Activation — Consultants & Strategic Partners | Refer Labs",
    description:
      "We find and activate consultants, strategic advisors, and relevant creators as ongoing distribution channels. Commercial terms, tracked performance, compounding reach.",
    url: `${SITE_URL}/services/partner-activation`,
    keywords: ["partner activation", "consultant partnerships", "strategic partners", "influencer marketing", "network activation"],
  },

  partnerActivation: {
    title: "Partner Activation — Consultants & Strategic Partners | Refer Labs",
    description:
      "We find and activate consultants, advisors, operators, and relevant creators as ongoing distribution channels. Structured commercial terms, attribution tracking, and compounding partner reach.",
    url: `${SITE_URL}/services/partner-activation`,
    keywords: ["partner activation", "consultant distribution", "strategic partner marketing", "B2B partner program", "influencer partnerships"],
  },

  apacExpansion: {
    title: "Australia Market Entry Partner — Refer Labs",
    description:
      "We partner with businesses to run and grow Australian operations. Local distribution networks, partner relationships, embedded commercial capability.",
    url: `${SITE_URL}/services/apac-expansion`,
    keywords: [
      "australia market entry partner",
      "expand business to australia",
      "australia market entry strategy",
      "apac expansion partner",
      "enter australian market",
      "australia business expansion",
      "distribution partner australia",
      "apac market entry service",
      "australia go to market partner",
      "australian market entry consultant",
      "how to enter the australian market",
      "apac distribution partner",
      "b2b market entry australia",
      "australian operations partner",
      "australia sales partner",
      "distribution network australia",
      "international business australia",
      "enter apac market",
      "australia expansion strategy",
      "apac business partner",
    ],
  },

  productDistribution: {
    title: "Co-Found a Distribution-First Business | Refer Labs",
    description:
      "We co-found businesses built to grow through affiliates and strategic partners. Multiple successful ventures launched. Enquire if you have an idea but need the GTM execution.",
    url: `${SITE_URL}/services/product-distribution`,
    keywords: ["co-founder GTM", "distribution-first business", "affiliate-led growth", "business co-founding", "GTM strategy partner"],
  },

  bestWebsiteBuilder: {
    title: "Best Website Builder 2026 — AI, Free & Fast Compared",
    description:
      "Best website builders 2026 — Carrd (free), Durable AI (30s build), Butternut, Swipe Pages. Honest reviews, pricing, free trials, Reddit verdict.",
    url: `${SITE_URL}/best-website-builder`,
    keywords: [
      "best website builder 2026",
      "best website builder",
      "AI website builder 2026",
      "AI website builder comparison",
      "free website builder no credit card",
      "website builder discount",
      "website builder free trial",
      "website builder deals 2026",
      "best website builder reddit 2026",
      "website builder reddit",
      "AI website builder reddit",
      "butternut vs durable vs carrd",
      "carrd vs durable vs butternut",
      "website builder for startups 2026",
      "easiest website builder 2026",
      "cheapest website builder 2026",
      "no code website builder 2026",
      "website builder for small business 2026",
      "fastest AI website builder",
      "best landing page builder 2026",
      "website builder comparison 2026",
      "build a website free 2026",
    ],
  },

  swipePages: {
    title: "Swipe Pages Review 2026: 14-Day Free Trial, AMP Landing Pages | Refer Labs",
    description:
      "Swipe Pages review 2026 — AMP landing pages that load in under 1 second, A/B testing, dynamic text replacement. 14-day free trial, no credit card. Compare vs Unbounce, Leadpages, and Instapage.",
    url: `${SITE_URL}/swipepages`,
    keywords: [
      "swipe pages review 2026",
      "swipe pages review",
      "swipe pages discount code",
      "swipe pages promo code",
      "swipe pages free trial",
      "swipe pages no credit card",
      "swipe pages vs unbounce",
      "swipe pages vs leadpages",
      "swipe pages vs instapage",
      "swipe pages alternatives",
      "swipe pages pricing 2026",
      "swipe pages reddit",
      "swipe pages reddit 2026",
      "AMP landing page builder 2026",
      "AMP landing page builder",
      "landing page builder Google Ads 2026",
      "best landing page builder 2026",
      "fastest landing page builder",
      "conversion rate optimisation landing pages",
      "landing page builder for paid ads",
    ],
  },

  butternut: {
    title: "Butternut AI Review 2026: Generate a Website Free in 20 Seconds | Refer Labs",
    description:
      "Butternut AI review 2026 — full website generated from a prompt in 20 seconds, free to try with no account. Compare Butternut AI vs Durable AI, Wix, Squarespace. Pricing, discount, and free trial link inside.",
    url: `${SITE_URL}/butternut`,
    keywords: [
      "butternut ai review 2026",
      "butternut ai review",
      "butternut ai discount code",
      "butternut ai discount 2026",
      "butternut ai promo code",
      "butternut ai free trial",
      "butternut ai free",
      "butternut ai vs durable",
      "butternut ai vs wix",
      "butternut ai vs squarespace",
      "butternut ai alternatives 2026",
      "butternut ai pricing 2026",
      "butternut ai reddit",
      "butternut ai reddit 2026",
      "AI website generator 2026",
      "best AI website builder 2026",
      "butternut ai small business",
      "AI website builder free no account",
      "generate website with AI free",
    ],
  },

  carrd: {
    title: "Carrd Review 2026 — Free Website Builder | Refer Labs",
    description:
      "Carrd review 2026 — free plan forever, Pro from $9/year. The simplest one-page website builder for portfolios, link-in-bio, and landing pages.",
    url: `${SITE_URL}/carrd`,
    keywords: [
      "carrd review 2026",
      "carrd review",
      "carrd discount code",
      "carrd free website builder",
      "carrd free plan",
      "carrd pro pricing 2026",
      "carrd vs squarespace 2026",
      "carrd vs webflow",
      "carrd alternatives 2026",
      "carrd promo code",
      "one page website builder 2026",
      "simple website builder free",
      "carrd reddit 2026",
      "carrd reddit",
      "carrd portfolio 2026",
      "carrd link in bio free",
      "is carrd worth it",
      "carrd.co free plan",
      "website builder under $10 per year",
      "cheapest website builder 2026",
    ],
  },

  durableAi: {
    title: "Durable AI Review 2026: AI Website Builder Free Trial for Small Business | Refer Labs",
    description:
      "Durable AI review 2026 — generate a complete business website in 30 seconds, free with no account. Includes CRM, invoicing, and Google Business integration. Compare Durable AI vs Wix, Squarespace, and Butternut AI.",
    url: `${SITE_URL}/durableai`,
    keywords: [
      "durable ai review 2026",
      "durable ai review",
      "durable ai discount",
      "durable ai discount 2026",
      "durable ai free trial",
      "durable ai free",
      "durable ai no account",
      "durable ai promo code",
      "AI website builder 2026",
      "AI website generator free",
      "durable ai vs wix 2026",
      "durable ai vs squarespace",
      "durable ai vs butternut",
      "durable ai alternatives 2026",
      "best AI website builder small business 2026",
      "durable website builder review",
      "durable ai reddit",
      "durable ai reddit 2026",
      "AI website builder for service business",
      "website builder with CRM free",
    ],
  },

  beehiiv: {
    title: "beehiiv Review 2026 — vs Substack | Refer Labs",
    description:
      "beehiiv review 2026 — newsletter platform free up to 2,500 subscribers. Built-in ad network, referral program, paid subscriptions. Compare vs Substack.",
    url: `${SITE_URL}/beehiiv`,
    keywords: [
      "beehiiv review 2026",
      "beehiiv review",
      "beehiiv free trial 2026",
      "beehiiv discount 2026",
      "beehiiv discount",
      "beehiiv promo code",
      "beehiiv vs substack 2026",
      "beehiiv vs substack",
      "beehiiv vs convertkit 2026",
      "beehiiv alternatives 2026",
      "beehiiv pricing 2026",
      "beehiiv ad network",
      "beehiiv reddit 2026",
      "beehiiv reddit",
      "best newsletter platform 2026",
      "grow newsletter free",
      "newsletter monetization platform",
      "beehiiv 14 day trial",
      "beehiiv free plan",
      "substack alternative 2026",
    ],
  },

  incomeLab: {
    title: "AI Side Hustle Ideas 2026 | How to Make Money With AI | Refer Labs",
    description:
      "Looking for the best AI side hustle ideas in 2026, AI passive income strategies, or what Reddit says about making money with AI? This page covers AI tools, business ideas, and automated income models — and takes you directly to Income Lab.",
    url: `${SITE_URL}/incomelab`,
    keywords: [
      "AI side hustle",
      "AI side hustle ideas",
      "make money with AI",
      "extra income with AI",
      "AI passive income",
      "best AI side hustles",
      "Reddit side hustle",
      "Reddit AI side hustle",
      "Reddit learn AI",
      "how to make money with AI",
      "AI business ideas",
      "AI online income",
      "AI tools to make money",
      "automate income with AI",
    ],
  },

  moshHair: {
    title: "Mosh Hair Loss Discount Code Australia 2026 | Mosh Promo Code, Cost & Review | Refer Labs",
    description:
      "Mosh hair loss discount code Australia 2026 — access the current Mosh referral offer, no code required. Covers Mosh cost and pricing, finasteride and minoxidil access, Mosh vs Dense, reviews, and what Reddit says about Mosh Australia.",
    url: `${SITE_URL}/moshhair`,
    keywords: [
      "mosh hair discount code",
      "mosh hair discount code australia",
      "mosh discount code 2026",
      "mosh hair loss australia",
      "mosh promo code australia",
      "mosh promo code 2026",
      "mosh referral code",
      "mosh referral link",
      "mosh coupon australia",
      "mosh sale",
      "mosh hair loss review",
      "mosh reddit",
      "mosh reddit australia",
      "mosh hair treatment australia",
      "mosh discount australia",
      "mosh hair loss treatment australia",
      "mosh hair review 2026",
      "is mosh legit",
      "mosh vs keeps australia",
      "australian hair loss telehealth",
      "mosh hair loss cost",
      "how much does mosh cost",
      "mosh hair loss price australia",
      "mosh subscription cost",
      "mosh finasteride australia",
      "mosh minoxidil australia",
      "finasteride australia online",
      "minoxidil australia telehealth",
      "mosh vs dense hair experts",
      "mosh hair loss results",
      "how long does mosh take to work",
      "mosh hair loss reddit australia",
    ],
  },

  dense: {
    title: "Dense Discount Code Australia | Dense Hair Experts Promo Code & Current Offer | Refer Labs",
    description:
      "Looking for a Dense discount code, promo code, or coupon? Access the current Dense Hair Experts offer through our affiliate link and shop Australia's leading hair density specialists.",
    url: `${SITE_URL}/dense`,
    keywords: [
      "dense discount code",
      "dense promo code",
      "dense sale",
      "dense hair discount",
      "dense hair experts code",
      "dense coupon",
      "dense offer australia",
      "dense hair experts promo code",
      "dense hair experts discount",
      "dense hair experts australia",
    ],
  },

  moshy: {
    title: "Moshy Discount Code Australia 2026 — Referral Link | Refer Labs",
    description:
      "Current Moshy referral link — no code required. An independent look at how the Moshy weight-loss telehealth service works, the online eligibility process, and prescription GLP-1 access in Australia. Information only — not medical advice.",
    url: `${SITE_URL}/moshy`,
    keywords: [
      "moshy discount code",
      "moshy discount code australia",
      "moshy discount code 2026",
      "moshy promo code",
      "moshy promo code 2026",
      "moshy referral code",
      "moshy referral link",
      "moshy coupon australia",
      "moshy weight loss discount",
      "moshy weight loss australia",
      "moshy weight loss review",
      "moshy weight loss reddit",
      "moshy review australia",
      "moshy reddit",
      "moshy reddit australia",
      "is moshy legit",
      "is moshy worth it",
      "moshy vs juniper",
      "moshy vs juniper 2026",
      "moshy vs juniper australia",
      "moshy eligibility quiz",
      "moshy eligibility check",
      "moshy semaglutide australia",
      "moshy GLP-1 australia",
      "moshy weight loss cost",
      "moshy cost australia",
      "how much does moshy cost",
      "moshy subscription cost",
      "moshy ozempic australia",
      "getmoshy discount",
      "getmoshy referral",
      "moshy review 2026",
      "australian weight loss telehealth",
      "online weight loss australia 2026",
    ],
  },

  apolloPeptides: {
    title: "Apollo Peptide Sciences Discount Code | Peptides Sale & Research Peptides Deals | Refer Labs",
    description:
      "Looking for an Apollo Peptide Sciences discount code? Discover the latest peptides sale and research peptide deals. Save on high-quality lab peptides — Semaglutide, CJC-1295, GHK-Cu, Ipamorelin, and Retatrutide research compounds.",
    url: `${SITE_URL}/apollopeptides`,
    keywords: [
      "apollo peptide sciences discount code",
      "apollo peptide sciences promo code",
      "apollo peptide sciences sale",
      "apollo peptide sciences review",
      "apollo peptide sciences reddit",
      "apollo peptides discount",
      "peptides sale",
      "research peptides sale",
      "research peptides deals",
      "peptide discount code",
      "buy peptides online",
      "research peptides supplier",
      "peptide supplier discount",
      "semaglutide research peptides",
      "CJC-1295 research peptides",
      "ipamorelin research peptides",
      "GHK-Cu peptide",
      "retatrutide research peptides",
      "peptides sale online",
      "best peptide supplier discount",
      "peptide research compounds sale",
    ],
  },

  ascensionPeptides: {
    title: "Ascension Peptides Discount Code | Research Peptides Sale & Deals | Refer Labs",
    description:
      "Find the latest Ascension Peptides discount codes and peptides sale offers. Save on high-purity research peptides for hormone signalling, metabolic, and anti-aging studies. Access the current deal via our referral link.",
    url: `${SITE_URL}/ascensionpeptides`,
    keywords: [
      "ascension peptides discount code",
      "ascension peptides promo code",
      "ascension peptides sale",
      "ascension peptides review",
      "ascension peptides reddit",
      "peptides sale",
      "research peptides sale",
      "research peptide deals",
      "peptide research compounds",
      "peptide supplier sale",
      "buy peptides online",
      "peptide supplier discount",
      "research peptides online",
      "lab grade peptides sale",
      "peptides sale online",
      "research peptides discount code",
      "peptide supplier deals",
    ],
  },

  bioPeptiTech: {
    title: "BioPeptiTech Discount Code | Peptides Sale & Research Peptides Deals | Refer Labs",
    description:
      "Find the latest BioPeptiTech discount codes and peptides sale offers. Compare research peptide deals and save on lab-grade peptide compounds for longevity, metabolic, and hormone signalling research.",
    url: `${SITE_URL}/biopeptitech`,
    keywords: [
      "biopeptitech discount code",
      "biopeptitech promo code",
      "biopeptitech sale",
      "biopeptitech review",
      "biopeptitech reddit",
      "peptides sale",
      "research peptides sale",
      "peptide discount code",
      "buy peptides online",
      "peptide supplier discounts",
      "peptide research compounds sale",
      "research peptides discount code",
      "peptide supplier deals",
      "peptides sale online",
      "best peptide supplier discount",
      "longevity research peptides",
      "metabolic research peptides",
    ],
  },

  bestPeptideSupplier: {
    title: "Best Peptide Supplier 2026: Apollo, Ascension & BioPeptiTech Compared | Refer Labs",
    description:
      "Compare the best research peptide suppliers in 2026 — Apollo Peptide Sciences, Ascension Peptides, and BioPeptiTech. Current discount codes, peptides sale offers, purity standards, and catalogue coverage. For research use only.",
    url: `${SITE_URL}/best-peptide-supplier`,
    keywords: [
      "best peptide supplier 2026",
      "best research peptide supplier",
      "peptides sale",
      "research peptides comparison",
      "peptide discount code",
      "buy peptides online",
      "peptide supplier review",
      "apollo peptide sciences review",
      "ascension peptides review",
      "biopeptitech review",
      "research peptide suppliers reddit",
      "peptide supplier comparison",
      "lab grade peptides",
      "best peptide supplier reddit",
      "peptide suppliers australia",
      "apollo vs ascension peptides",
      "peptide supplier discount",
      "research peptides deals",
      "top peptide suppliers",
      "peptide purity coa",
    ],
  },

  bestWeightLossTelehealth: {
    title: "Best Weight Loss Telehealth Australia 2026: Moshy vs Juniper vs Better Being | Refer Labs",
    description:
      "Compare the best weight loss telehealth platforms in Australia 2026 — Moshy, Juniper, and Better Being. GLP-1 access, eligibility process, pricing, and Reddit verdict. Find the right online weight management program for you.",
    url: `${SITE_URL}/best-weight-loss-telehealth-australia`,
    keywords: [
      "best weight loss telehealth australia 2026",
      "best weight loss telehealth australia",
      "moshy vs juniper",
      "moshy vs juniper australia",
      "moshy vs juniper vs better being",
      "online weight loss australia 2026",
      "weight loss telehealth australia",
      "GLP-1 telehealth australia",
      "semaglutide telehealth australia",
      "moshy weight loss review",
      "juniper weight loss review",
      "better being australia",
      "australian weight loss program comparison",
      "best online weight management australia",
      "weight loss program australia 2026",
      "weight loss medication telehealth australia",
      "telehealth weight loss reddit australia",
      "moshy vs juniper reddit",
    ],
  },

  moshyVsJuniper: {
    title: "Moshy vs Juniper 2026: Which Weight Loss Telehealth Is Right for You? | Refer Labs",
    description:
      "Moshy vs Juniper compared for 2026 — Moshy is for men, Juniper is for women. GLP-1 access, eligibility, cost model, coaching, and the Reddit verdict. Find which Australian weight-loss telehealth fits you.",
    url: `${SITE_URL}/moshy-vs-juniper`,
    keywords: [
      "moshy vs juniper",
      "moshy vs juniper 2026",
      "moshy vs juniper australia",
      "moshy vs juniper reddit",
      "moshy or juniper",
      "juniper vs moshy weight loss",
      "moshy weight loss australia",
      "juniper weight loss australia",
      "best glp-1 telehealth australia",
      "semaglutide telehealth australia",
      "weight loss telehealth australia 2026",
      "moshy review",
      "juniper review",
      "moshy men weight loss",
      "juniper women weight loss",
    ],
  },

  carrdVsDurable: {
    title: "Carrd vs Durable AI 2026: Which Website Builder Should You Use? | Refer Labs",
    description:
      "Carrd vs Durable AI compared for 2026 — Carrd is the cheapest one-page builder; Durable AI generates a full business site with CRM in 30 seconds. Pricing, AI, free plans, and which to pick.",
    url: `${SITE_URL}/carrd-vs-durable`,
    keywords: [
      "carrd vs durable",
      "carrd vs durable ai",
      "carrd vs durable 2026",
      "durable vs carrd",
      "best cheap website builder 2026",
      "ai website builder vs carrd",
      "carrd alternative",
      "durable ai alternative",
      "one page website builder vs ai website builder",
      "cheapest website builder 2026",
    ],
  },

  comparisonWebsite: {
    title: "Australia's Curated Health & Performance Comparison Platform | Refer Labs",
    description:
      "A properly researched comparison platform across five health and performance categories in Australia — ED, weight loss, hair loss, testosterone, and supplements. Not a pay-to-rank directory.",
    url: `${SITE_URL}/comparison-website`,
    keywords: [
      "best ED clinics Australia",
      "best weight loss programs Australia",
      "hair loss treatment Australia",
      "TRT clinic Australia",
      "testosterone clinic Australia",
      "Australian health comparison",
      "supplements Australia comparison",
      "men's health Australia",
      "health platform Australia",
      "performance health Australia",
    ],
  },

  bestNewsletterPlatform: {
    title: "Best Newsletter Platform 2026 — beehiiv vs Substack",
    description:
      "Best newsletter platforms 2026 — beehiiv vs Substack vs ConvertKit. Free plans, monetisation, growth tools, and Reddit verdict for each.",
    url: `${SITE_URL}/best-newsletter-platform`,
    keywords: [
      "best newsletter platform 2026",
      "best newsletter platform",
      "beehiiv vs substack 2026",
      "beehiiv vs substack vs convertkit",
      "newsletter platform comparison 2026",
      "newsletter platform reddit 2026",
      "newsletter platform reddit",
      "substack alternative 2026",
      "best email newsletter platform",
      "newsletter monetization platform 2026",
      "grow newsletter 2026",
      "beehiiv review 2026",
      "substack vs convertkit",
      "newsletter platform free plan",
      "best platform for newsletter creators",
    ],
  },

  bestHairLossTreatmentAustralia: {
    title: "Best Hair Loss Treatment Australia 2026: Mosh vs Dense vs Telehealth Options | Refer Labs",
    description:
      "Compare the best hair loss treatments in Australia 2026 — Mosh, Dense Hair Experts, and telehealth options. Clinical vs topical approaches, pricing, and what Reddit says about Australian hair loss solutions.",
    url: `${SITE_URL}/best-hair-loss-treatment-australia`,
    keywords: [
      "best hair loss treatment australia 2026",
      "best hair loss treatment australia",
      "mosh hair loss review australia",
      "dense hair experts review",
      "hair loss telehealth australia 2026",
      "finasteride australia telehealth",
      "minoxidil australia review",
      "hair loss treatment australia reddit",
      "mosh vs dense australia",
      "australian hair loss comparison",
      "hair loss clinic australia",
      "hair thinning treatment australia",
      "hair loss treatment reddit australia",
      "best hair loss products australia 2026",
    ],
  },

  guides: {
    title: "Guides & Comparisons | Refer Labs",
    description:
      "Honest comparison guides covering health providers, website builders, newsletter platforms, peptide suppliers, and business tools — Australia and global.",
    url: `${SITE_URL}/guides`,
    keywords: [
      "comparison guides australia",
      "product comparison reviews",
      "best health tools australia",
      "affiliate product reviews",
      "independent product comparisons",
    ],
  },

  // Secondary pages
  roiCalculator: {
    title: "Australia Expansion Estimator - ROI Calculator",
    description: "Estimate the ROI of entering Australia with Refer Labs. Model your 90-day pilot returns by industry, deal size, and engagement scope.",
    url: `${SITE_URL}/roi-calculator`,
    keywords: [
      "Australia expansion ROI",
      "market entry calculator",
      "Australia GTM ROI",
      "expansion cost estimator",
    ],
  },

  leadHacking: {
    title: "Partner Sourcing & Activation for Australia",
    description: "We systematically source, qualify, and activate Australian partners - agencies, LinkedIn creators, and advisors - to build your distribution channel.",
    url: `${SITE_URL}/lead-hacking`,
    keywords: [
      "Australia partner sourcing",
      "Australian agency partners",
      "partner activation Australia",
      "distribution partner sourcing",
    ],
  },

  partnerProgram: {
    title: "Partner Program - Become a Refer Labs partner",
    description: "Join the Refer Labs partner program and earn recurring revenue.",
    url: `${SITE_URL}/our-affiliate-program`,
  },

  linkedinInfluencer: {
    title: "LinkedIn Creator Partnerships for Australia Market Entry",
    description: "Partner with verified Australian LinkedIn creators to build credibility, generate leads, and accelerate your market entry. Full-service partnership management.",
    url: `${SITE_URL}/linkedin-growth`,
    keywords: [
      "LinkedIn creator partnerships Australia",
      "Australian LinkedIn influencers",
      "B2B creator marketing Australia",
      "LinkedIn market entry Australia",
    ],
  },

  linkedinInfluencerCreator: {
    title: "Join as an Australian LinkedIn Creator",
    description: "Help overseas companies enter Australia and earn performance-based commissions. Join our curated pool of Australian LinkedIn creators.",
    url: `${SITE_URL}/linkedin-growth/influencer`,
    keywords: [
      "LinkedIn creator program Australia",
      "Australian creator partnerships",
      "earn from LinkedIn Australia",
    ],
  },

  linkedinInfluencerBusiness: {
    title: "Launch Australian Creator Campaigns for Market Entry",
    description: "Launch performance-based LinkedIn creator campaigns to build awareness and generate leads in the Australian market.",
    url: `${SITE_URL}/linkedin-growth/business`,
    keywords: [
      "Australian creator campaigns",
      "LinkedIn marketing Australia",
      "creator partnerships market entry",
    ],
  },

  financialAdvisorsService: {
    title: "Services for Financial Advisors",
    description: "Partner programs for financial advisors and planners.",
    url: `${SITE_URL}/services/financial-advisors`,
  },

  accountantsService: {
    title: "Services for Accountants",
    description: "Partner programs for accounting firms.",
    url: `${SITE_URL}/services/accountants`,
  },

  consultantsCoachesService: {
    title: "Services for Consultants & Coaches",
    description: "Partner programs for consultants and coaches.",
    url: `${SITE_URL}/services/consultants-coaches`,
  },

  recruitersStaffingService: {
    title: "Services for Recruiters & Staffing",
    description: "Partner programs for recruiters and staffing firms.",
    url: `${SITE_URL}/services/recruiters-staffing`,
  },

  insuranceBrokersService: {
    title: "Services for Insurance Brokers",
    description: "Partner programs for insurance brokers.",
    url: `${SITE_URL}/services/insurance-brokers`,
  },

  referralPartnerships: {
    title: "Referral & Affiliate Partnerships - Build Your Australian Partner Channel",
    description:
      "We source, activate, and manage referral and affiliate partners across Australia. Agencies, consultants, creators, and strategic allies - all tracked and managed end-to-end.",
    url: `${SITE_URL}/referral-partnerships`,
    keywords: [
      "referral partnerships Australia",
      "affiliate channel Australia",
      "partner program management",
      "Australian referral partners",
      "distribution activation Australia",
    ],
  },

  affiliatePartnerships: {
    title: "Services - Sales Representation, Partnerships & Distribution Deals",
    description:
      "Three core services: Sales Representation, Partnership Development, and Distribution Deals for overseas companies entering Australia.",
    url: `${SITE_URL}/services`,
    keywords: [
      "Australia sales services",
      "Australian partnership services",
    ],
  },

  referralBlueprint: {
    title: "250+ Affiliate Programs Database — $799 | Refer Labs",
    description:
      "250+ vetted affiliate programs in Excel + personalised strategy brief, SEO concepts, distribution playbooks, niche brief. $799 AUD, 48hr delivery.",
    url: `${SITE_URL}/referral-blueprint`,
    keywords: [
      "affiliate program database australia",
      "best affiliate programs australia 2026",
      "affiliate marketing blueprint australia",
      "how to start affiliate marketing australia",
      "referral program list australia",
      "affiliate income blueprint",
      "affiliate marketing starter pack",
      "best recurring affiliate programs australia",
      "build affiliate business from scratch",
      "affiliate marketing side hustle australia",
      "passive income affiliate programs",
      "affiliate program database excel",
      "affiliate marketing strategy plan",
      "referral marketing business plan",
      "saas affiliate programs list",
      "high commission affiliate programs australia",
      "affiliate programs health australia",
      "affiliate programs fintech australia",
      "referral growth blueprint",
      "affiliate niche selection guide",
      "seo affiliate marketing australia",
    ],
  },

  dashboard: {
    title: "Dashboard",
    description: "Manage your program, track performance, and view reporting.",
    url: `${SITE_URL}/dashboard`,
    noIndex: true,
  },

  login: {
    title: "Login - Access your dashboard",
    description: "Log in to your Refer Labs account to manage your program and track progress.",
    url: `${SITE_URL}/login`,
    noIndex: true,
  },
};
