import { Metadata } from "next";

export interface SEOConfig {
  title: string;
  description: string;
  keywords?: string[];
  image?: string;
  url?: string;
  type?: "website" | "article";
  noIndex?: boolean;
}

const SITE_NAME = "Refer Labs";
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://referlabs.com.au";
const TWITTER_HANDLE = "@referlabs";

/** Per-page, branded Open Graph card generated by /og from the page title. */
function dynamicOgImage(title: string): string {
  return `${SITE_URL}/og?title=${encodeURIComponent(title)}`;
}

/**
 * Generate comprehensive metadata for SEO, Open Graph, and Twitter Cards
 */
export function generateMetadata(config: SEOConfig): Metadata {
  const {
    title,
    description,
    keywords = [],
    image,
    url,
    type = "website",
    noIndex = false,
  } = config;

  const fullTitle = title.includes(SITE_NAME) ? title : `${title} | ${SITE_NAME}`;
  const canonicalUrl = url || SITE_URL;
  // Each page gets a unique, branded OG card built from its title unless an
  // explicit image is supplied — lifts social/SERP click-through site-wide.
  const ogImage = image || dynamicOgImage(title);

  return {
    metadataBase: new URL(SITE_URL),
    title: fullTitle,
    description,
    keywords: keywords.length > 0 ? keywords.join(", ") : undefined,

    // Robots
    robots: noIndex
      ? {
          index: false,
          follow: false,
        }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
          },
        },

    // Open Graph
    openGraph: {
      title: fullTitle,
      description,
      url: canonicalUrl,
      siteName: SITE_NAME,
      images: [
        {
          url: ogImage,
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
      locale: "en_AU",
      type,
    },

    // Twitter Card
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
      images: [ogImage],
      creator: TWITTER_HANDLE,
      site: TWITTER_HANDLE,
    },

    // Additional meta tags
    alternates: {
      canonical: canonicalUrl,
    },

    // Verification tags
    verification: {
      google: process.env.NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION,
    },

    // App-specific metadata
    applicationName: SITE_NAME,

    // Referrer policy
    referrer: "origin-when-cross-origin",

    // Category
    category: "Business Services",

    // Authors
    authors: [{ name: SITE_NAME }],

    // Creator
    creator: SITE_NAME,

    // Publisher
    publisher: SITE_NAME,

    // Format detection
    formatDetection: {
      email: false,
      address: false,
      telephone: false,
    },

    // Icons
    icons: {
      icon: "/logo.svg",
      apple: "/logo.svg",
    },

    // Manifest
    manifest: "/manifest.json",
  };
}

/**
 * Pre-configured SEO configs for common pages
 */
export const seoConfig = {
  home: {
    title: "Refer Labs: Independent Health, Software & Tool Comparisons, Australia",
    description:
      "Independent comparisons for Australians. Weight loss telehealth, hair loss treatment, website builders, newsletter platforms and more, researched properly so you can choose with confidence.",
    url: SITE_URL,
    keywords: [
      "comparison site australia",
      "compare telehealth australia",
      "weight loss telehealth comparison",
      "compare website builders australia",
      "independent product comparisons australia",
      "best providers australia",
      "compare services australia",
      "refer labs",
    ],
  },

  weightLossHub: {
    title: "Weight Loss Telehealth Australia 2026: Compare Online Programs & Clinics | Refer Labs",
    description:
      "Compare online weight loss telehealth in Australia. How medical telehealth clinics, coaching programs and the GP pathway differ, plus independent guides to Moshy, Juniper and more. Information only, not medical advice.",
    url: `${SITE_URL}/weight-loss`,
    keywords: [
      "weight loss telehealth australia",
      "online weight loss programs australia",
      "weight loss clinic online australia",
      "online weight loss australia",
      "weight loss australia",
      "compare weight loss programs australia",
      "weight loss services australia",
      "how to choose a weight loss program",
    ],
  },

  forBusiness: {
    title: "For Business: Partner With Refer Labs",
    description:
      "Get your product featured in Refer Labs comparisons, or work with our team on referral programs, affiliate distribution and Australian market entry. Partnerships disclosed, rankings never sold.",
    url: `${SITE_URL}/for-business`,
    keywords: [
      "partner with refer labs",
      "get featured comparison site australia",
      "referral program agency australia",
      "affiliate distribution service",
      "customer acquisition australia",
    ],
  },

  pricing: {
    title: "Pricing - Market Entry Engagement Models",
    description:
      "Choose the right engagement model for your APAC expansion. Retainer + commission pricing aligned to your growth stage. 90-day pilot structure.",
    url: `${SITE_URL}/pricing`,
    keywords: [
      "market entry pricing",
      "GTM services pricing",
      "expansion engagement cost",
      "partnership services pricing",
      "outsourced sales pricing",
    ],
  },

  howItWorks: {
    title: "How It Works: Refer Labs Growth & Distribution Engine",
    description:
      "See how Refer Labs builds and activates your growth engine — referral programs, affiliate distribution, influencer channels, APAC expansion, and digital products end to end.",
    url: `${SITE_URL}/how-it-works`,
    keywords: [
      "how referral programs work",
      "affiliate distribution process",
      "growth engine setup",
      "distribution channel activation",
      "referral marketing process",
    ],
  },

  services: {
    title: "Services: Five Growth Engines | Refer Labs",
    description:
      "Five growth engines: Referral Program Launch, Elite Affiliate Distribution, Influencer & Network Activation, APAC Market Expansion, and Product Creation & Distribution.",
    url: `${SITE_URL}/services`,
    keywords: [
      "referral program launch",
      "affiliate distribution service",
      "influencer activation agency",
      "APAC market expansion",
      "product distribution service",
      "growth engine agency",
    ],
  },

  whoItsFor: {
    noIndex: true,
    title: "Who It's For: B2B & B2C Businesses Ready to Scale | Refer Labs",
    description:
      "Refer Labs works with SMBs, eCommerce brands, SaaS companies, and global operators who want to build referral programs, activate distribution channels, and scale through structured growth.",
    url: `${SITE_URL}/who-its-for`,
    keywords: [
      "referral program for SMB",
      "affiliate channel for ecommerce",
      "B2B distribution partner",
      "growth partner for SaaS",
      "who is refer labs for",
    ],
  },

  caseStudies: {
    noIndex: true,
    title: "Playbooks: Growth & Distribution Examples | Refer Labs",
    description:
      "Example playbooks showing how we launch referral programs, activate affiliate and influencer channels, distribute digital products, and expand into APAC.",
    url: `${SITE_URL}/case-studies`,
    keywords: [
      "referral program examples",
      "affiliate distribution playbook",
      "growth engine examples",
      "distribution channel playbook",
    ],
  },

  about: {
    title: "About Refer Labs: Australia's Independent Comparison Platform",
    description:
      "Refer Labs helps Australians choose between health services, software and tools through independent, disclosed comparisons, and helps businesses reach qualified buyers. Rankings are never sold.",
    url: `${SITE_URL}/about`,
    keywords: [
      "about refer labs",
      "independent comparison platform australia",
      "refer labs review site",
      "comparison site australia",
    ],
  },

  hairLossHub: {
    title: "Hair Loss in Australia 2026: Compare Treatments & Your Options | Refer Labs",
    description:
      "The hair loss decision, organised. Compare Australia's clinical telehealth and topical products, with independent guides to Mosh, Dense and more. Information only, not medical advice.",
    url: `${SITE_URL}/hair-loss`,
    keywords: [
      "hair loss australia",
      "hair loss treatment australia",
      "hair loss options australia",
      "compare hair loss treatments australia",
      "hair loss telehealth australia",
      "how to treat hair loss australia",
    ],
  },

  contact: {
    title: "Contact Refer Labs: Partner With Us",
    description:
      "Get in touch with Refer Labs. Book a call to discuss referral programs, affiliate distribution, influencer activation, APAC expansion, or product distribution.",
    url: `${SITE_URL}/contact`,
    keywords: [
      "contact refer labs",
      "book a call refer labs",
      "referral program consultation",
      "affiliate distribution enquiry",
    ],
  },

  faq: {
    title: "FAQ: Refer Labs Growth & Distribution Services",
    description:
      "Find answers to common questions about our referral programs, affiliate distribution, influencer activation, APAC expansion, and product distribution services.",
    url: `${SITE_URL}/faq`,
    keywords: [
      "refer labs FAQ",
      "referral program questions",
      "affiliate distribution FAQ",
      "growth services questions",
    ],
  },

  application: {
    title: "Apply to Work With Refer Labs",
    description:
      "Submit your application to work with Refer Labs. Tell us about your business, growth goals, and which services you need. We review every application and respond within 1-2 business days.",
    url: `${SITE_URL}/application`,
    keywords: [
      "apply refer labs",
      "referral program application",
      "work with refer labs",
      "growth partner application",
    ],
  },

  security: {
    title: "Security - Enterprise-grade data protection",
    description:
      "Learn about our security practices, data protection, and how we keep your business data safe and private.",
    url: `${SITE_URL}/security`,
    keywords: [
      "data security",
      "data protection",
      "enterprise security",
    ],
  },

  privacy: {
    title: "Privacy Policy - How we protect your data",
    description:
      "Read our privacy policy to understand how Refer Labs collects, uses, and protects your personal information.",
    url: `${SITE_URL}/privacy`,
    keywords: ["privacy policy", "data privacy", "data protection"],
  },

  terms: {
    title: "Terms of Service - Legal terms and conditions",
    description:
      "Read the terms of service for using Refer Labs, including user rights, responsibilities, and legal agreements.",
    url: `${SITE_URL}/terms`,
    keywords: ["terms of service", "legal terms", "user agreement"],
  },

  // Service landing pages
  referralPrograms: {
    title: "Referral Program Launch & Distribution AU | Refer Labs",
    description:
      "We design, launch, and actively distribute referral programs for B2B and B2C businesses. Incentive design, tracking, channel activation. Fully managed.",
    url: `${SITE_URL}/services/referral-programs`,
    keywords: [
      "referral program launch service",
      "referral program design",
      "referral program consultant australia",
      "how to launch a referral program",
      "referral marketing agency australia",
      "referral program setup service",
      "word of mouth marketing strategy",
      "referral program for saas",
      "referral program for ecommerce",
      "referral program management australia",
      "referral channel growth",
      "referral program incentive design",
      "referral tracking setup",
      "referral marketing program australia",
      "build a referral program",
      "customer referral program",
      "referral program strategy",
      "referral program distribution strategy",
      "referral growth service",
      "referral program optimisation",
    ],
  },

  affiliateDistribution: {
    title: "Affiliate Program Distribution Service | Refer Labs",
    description:
      "We distribute your affiliate offer into high-intent communities with an in-house team. Sector-exclusive representation. Source-level attribution tracking.",
    url: `${SITE_URL}/services/affiliate-distribution`,
    keywords: [
      "affiliate program management service",
      "affiliate distribution service",
      "affiliate marketing agency australia",
      "managed affiliate program",
      "outsource affiliate program management",
      "affiliate program distribution",
      "affiliate marketing management company",
      "affiliate program placement service",
      "affiliate community distribution",
      "grow affiliate program australia",
      "affiliate channel management",
      "b2b affiliate program distribution",
      "affiliate program launch and distribution",
      "affiliate distribution agency",
      "niche affiliate marketing placement",
      "reddit affiliate distribution",
      "affiliate program activation service",
      "affiliate program growth strategy",
      "affiliate marketing distribution channels",
      "affiliate program management australia",
    ],
  },

  influencerActivation: {
    noIndex: true,
    title: "Partner Activation: Consultants & Strategic Partners | Refer Labs",
    description:
      "We find and activate consultants, strategic advisors, and relevant creators as ongoing distribution channels. Commercial terms, tracked performance, compounding reach.",
    url: `${SITE_URL}/services/partner-activation`,
    keywords: ["partner activation", "consultant partnerships", "strategic partners", "influencer marketing", "network activation"],
  },

  partnerActivation: {
    title: "Partner Activation: Consultants & Strategic Partners | Refer Labs",
    description:
      "We find and activate consultants, advisors, operators, and relevant creators as ongoing distribution channels. Structured commercial terms, attribution tracking, and compounding partner reach.",
    url: `${SITE_URL}/services/partner-activation`,
    keywords: ["partner activation", "consultant distribution", "strategic partner marketing", "B2B partner program", "influencer partnerships"],
  },

  apacExpansion: {
    title: "Australia Market Entry Partner: Refer Labs",
    description:
      "We partner with businesses to run and grow Australian operations. Local distribution networks, partner relationships, embedded commercial capability.",
    url: `${SITE_URL}/services/apac-expansion`,
    keywords: [
      "australia market entry partner",
      "expand business to australia",
      "australia market entry strategy",
      "apac expansion partner",
      "enter australian market",
      "australia business expansion",
      "distribution partner australia",
      "apac market entry service",
      "australia go to market partner",
      "australian market entry consultant",
      "how to enter the australian market",
      "apac distribution partner",
      "b2b market entry australia",
      "australian operations partner",
      "australia sales partner",
      "distribution network australia",
      "international business australia",
      "enter apac market",
      "australia expansion strategy",
      "apac business partner",
    ],
  },

  productDistribution: {
    title: "Co-Found a Distribution-First Business | Refer Labs",
    description:
      "We co-found businesses built to grow through affiliates and strategic partners. Multiple successful ventures launched. Enquire if you have an idea but need the GTM execution.",
    url: `${SITE_URL}/services/product-distribution`,
    keywords: ["co-founder GTM", "distribution-first business", "affiliate-led growth", "business co-founding", "GTM strategy partner"],
  },

  bestWebsiteBuilder: {
    title: "Best Website Builder 2026: AI, Free & Fast Compared",
    description:
      "Best website builders 2026 — Carrd (free), Durable AI (30s build), Butternut, Swipe Pages. Honest reviews, pricing, free trials, Reddit verdict.",
    url: `${SITE_URL}/best-website-builder`,
    keywords: [
      "best website builder 2026",
      "best website builder",
      "AI website builder 2026",
      "AI website builder comparison",
      "free website builder no credit card",
      "website builder discount",
      "website builder free trial",
      "website builder deals 2026",
      "best website builder reddit 2026",
      "website builder reddit",
      "AI website builder reddit",
      "butternut vs durable vs carrd",
      "carrd vs durable vs butternut",
      "website builder for startups 2026",
      "easiest website builder 2026",
      "cheapest website builder 2026",
      "no code website builder 2026",
      "website builder for small business 2026",
      "fastest AI website builder",
      "best landing page builder 2026",
      "website builder comparison 2026",
      "build a website free 2026",
    ],
  },

  swipePages: {
    title: "Swipe Pages Review 2026: 14-Day Free Trial, AMP Landing Pages | Refer Labs",
    description:
      "Swipe Pages review 2026 — AMP landing pages that load in under 1 second, A/B testing, dynamic text replacement. 14-day free trial, no credit card. Compare vs Unbounce, Leadpages, and Instapage.",
    url: `${SITE_URL}/swipepages`,
    keywords: [
      "swipe pages review 2026",
      "swipe pages review",
      "swipe pages discount code",
      "swipe pages promo code",
      "swipe pages free trial",
      "swipe pages no credit card",
      "swipe pages vs unbounce",
      "swipe pages vs leadpages",
      "swipe pages vs instapage",
      "swipe pages alternatives",
      "swipe pages pricing 2026",
      "swipe pages reddit",
      "swipe pages reddit 2026",
      "AMP landing page builder 2026",
      "AMP landing page builder",
      "landing page builder Google Ads 2026",
      "best landing page builder 2026",
      "fastest landing page builder",
      "conversion rate optimisation landing pages",
      "landing page builder for paid ads",
    ],
  },

  butternut: {
    title: "Butternut AI Review 2026: Generate a Website Free in 20 Seconds | Refer Labs",
    description:
      "Butternut AI review 2026 — full website generated from a prompt in 20 seconds, free to try with no account. Compare Butternut AI vs Durable AI, Wix, Squarespace. Pricing, discount, and free trial link inside.",
    url: `${SITE_URL}/butternut`,
    keywords: [
      "butternut ai review 2026",
      "butternut ai review",
      "butternut ai discount code",
      "butternut ai discount 2026",
      "butternut ai promo code",
      "butternut ai free trial",
      "butternut ai free",
      "butternut ai vs durable",
      "butternut ai vs wix",
      "butternut ai vs squarespace",
      "butternut ai alternatives 2026",
      "butternut ai pricing 2026",
      "butternut ai reddit",
      "butternut ai reddit 2026",
      "AI website generator 2026",
      "best AI website builder 2026",
      "butternut ai small business",
      "AI website builder free no account",
      "generate website with AI free",
    ],
  },

  carrd: {
    title: "Carrd Review 2026: Free Website Builder | Refer Labs",
    description:
      "Carrd review 2026 — free plan forever, Pro from $9/year. The simplest one-page website builder for portfolios, link-in-bio, and landing pages.",
    url: `${SITE_URL}/carrd`,
    keywords: [
      "carrd review 2026",
      "carrd review",
      "carrd discount code",
      "carrd free website builder",
      "carrd free plan",
      "carrd pro pricing 2026",
      "carrd vs squarespace 2026",
      "carrd vs webflow",
      "carrd alternatives 2026",
      "carrd promo code",
      "one page website builder 2026",
      "simple website builder free",
      "carrd reddit 2026",
      "carrd reddit",
      "carrd portfolio 2026",
      "carrd link in bio free",
      "is carrd worth it",
      "carrd.co free plan",
      "website builder under $10 per year",
      "cheapest website builder 2026",
    ],
  },

  durableAi: {
    title: "Durable AI Review 2026: AI Website Builder Free Trial for Small Business | Refer Labs",
    description:
      "Durable AI review 2026 — generate a complete business website in 30 seconds, free with no account. Includes CRM, invoicing, and Google Business integration. Compare Durable AI vs Wix, Squarespace, and Butternut AI.",
    url: `${SITE_URL}/durableai`,
    keywords: [
      "durable ai review 2026",
      "durable ai review",
      "durable ai discount",
      "durable ai discount 2026",
      "durable ai free trial",
      "durable ai free",
      "durable ai no account",
      "durable ai promo code",
      "AI website builder 2026",
      "AI website generator free",
      "durable ai vs wix 2026",
      "durable ai vs squarespace",
      "durable ai vs butternut",
      "durable ai alternatives 2026",
      "best AI website builder small business 2026",
      "durable website builder review",
      "durable ai reddit",
      "durable ai reddit 2026",
      "AI website builder for service business",
      "website builder with CRM free",
    ],
  },

  beehiiv: {
    title: "beehiiv Review 2026: vs Substack | Refer Labs",
    description:
      "beehiiv review 2026 — newsletter platform free up to 2,500 subscribers. Built-in ad network, referral program, paid subscriptions. Compare vs Substack.",
    url: `${SITE_URL}/beehiiv`,
    keywords: [
      "beehiiv review 2026",
      "beehiiv review",
      "beehiiv free trial 2026",
      "beehiiv discount 2026",
      "beehiiv discount",
      "beehiiv promo code",
      "beehiiv vs substack 2026",
      "beehiiv vs substack",
      "beehiiv vs convertkit 2026",
      "beehiiv alternatives 2026",
      "beehiiv pricing 2026",
      "beehiiv ad network",
      "beehiiv reddit 2026",
      "beehiiv reddit",
      "best newsletter platform 2026",
      "grow newsletter free",
      "newsletter monetization platform",
      "beehiiv 14 day trial",
      "beehiiv free plan",
      "substack alternative 2026",
    ],
  },

  incomeLab: {
    title: "How to Make Money With AI in 2026: Real Side Hustles That Work",
    description:
      "Looking for the best AI side hustle ideas in 2026, AI passive income strategies, or what Reddit says about making money with AI? This page covers AI tools, business ideas, and automated income models — and takes you directly to Income Lab.",
    url: `${SITE_URL}/incomelab`,
    keywords: [
      "AI side hustle",
      "AI side hustle ideas",
      "make money with AI",
      "extra income with AI",
      "AI passive income",
      "best AI side hustles",
      "Reddit side hustle",
      "Reddit AI side hustle",
      "Reddit learn AI",
      "how to make money with AI",
      "AI business ideas",
      "AI online income",
      "AI tools to make money",
      "automate income with AI",
    ],
  },

  moshHair: {
    title: "Mosh Hair Loss Discount Code Australia 2026 | Mosh Promo Code, Cost & Review | Refer Labs",
    description:
      "Mosh hair loss discount code Australia 2026 — access the current Mosh referral offer, no code required. Covers Mosh cost and pricing, finasteride and minoxidil access, Mosh vs Dense, reviews, and what Reddit says about Mosh Australia.",
    url: `${SITE_URL}/moshhair`,
    keywords: [
      "mosh hair discount code",
      "mosh hair discount code australia",
      "mosh discount code 2026",
      "mosh hair loss australia",
      "mosh promo code australia",
      "mosh promo code 2026",
      "mosh referral code",
      "mosh referral link",
      "mosh coupon australia",
      "mosh sale",
      "mosh hair loss review",
      "mosh reddit",
      "mosh reddit australia",
      "mosh hair treatment australia",
      "mosh discount australia",
      "mosh hair loss treatment australia",
      "mosh hair review 2026",
      "is mosh legit",
      "mosh vs keeps australia",
      "australian hair loss telehealth",
      "mosh hair loss cost",
      "how much does mosh cost",
      "mosh hair loss price australia",
      "mosh subscription cost",
      "mosh finasteride australia",
      "mosh minoxidil australia",
      "finasteride australia online",
      "minoxidil australia telehealth",
      "mosh vs dense hair experts",
      "mosh hair loss results",
      "how long does mosh take to work",
      "mosh hair loss reddit australia",
    ],
  },

  dense: {
    title: "Dense Discount Code Australia | Dense Hair Experts Promo Code & Current Offer | Refer Labs",
    description:
      "Looking for a Dense discount code, promo code, or coupon? Access the current Dense Hair Experts offer through our affiliate link and shop Australia's leading hair density specialists.",
    url: `${SITE_URL}/dense`,
    keywords: [
      "dense discount code",
      "dense promo code",
      "dense sale",
      "dense hair discount",
      "dense hair experts code",
      "dense coupon",
      "dense offer australia",
      "dense hair experts promo code",
      "dense hair experts discount",
      "dense hair experts australia",
    ],
  },

  moshy: {
    title: "Moshy Weight Loss Australia 2026: Referral Link, Cost & How It Works | Refer Labs",
    description:
      "The current Moshy referral link, no code required. An independent look at how the Moshy weight-loss telehealth service works in Australia: the online eligibility check, what it costs, and how prescription GLP-1 access is handled. Information only, not medical advice.",
    url: `${SITE_URL}/moshy`,
    keywords: [
      "moshy discount code",
      "moshy discount code australia",
      "moshy discount code 2026",
      "moshy promo code",
      "moshy promo code 2026",
      "moshy referral code",
      "moshy referral link",
      "moshy coupon australia",
      "moshy weight loss discount",
      "moshy weight loss australia",
      "moshy weight loss review",
      "moshy weight loss reddit",
      "moshy review australia",
      "moshy reddit",
      "moshy reddit australia",
      "is moshy legit",
      "is moshy worth it",
      "moshy vs juniper",
      "moshy vs juniper 2026",
      "moshy vs juniper australia",
      "moshy eligibility quiz",
      "moshy eligibility check",
      "moshy semaglutide australia",
      "moshy GLP-1 australia",
      "moshy weight loss cost",
      "moshy cost australia",
      "how much does moshy cost",
      "moshy subscription cost",
      "getmoshy discount",
      "getmoshy referral",
      "moshy review 2026",
      "australian weight loss telehealth",
      "online weight loss australia 2026",
    ],
  },

  apolloPeptides: {
    title: "Apollo Peptide Sciences Discount Code | Peptides Sale & Research Peptides Deals | Refer Labs",
    description:
      "Looking for an Apollo Peptide Sciences discount code? Discover the latest peptides sale and research peptide deals. Save on high-quality lab peptides — Semaglutide, CJC-1295, GHK-Cu, Ipamorelin, and Retatrutide research compounds.",
    url: `${SITE_URL}/apollopeptides`,
    keywords: [
      "apollo peptide sciences discount code",
      "apollo peptide sciences promo code",
      "apollo peptide sciences sale",
      "apollo peptide sciences review",
      "apollo peptide sciences reddit",
      "apollo peptides discount",
      "peptides sale",
      "research peptides sale",
      "research peptides deals",
      "peptide discount code",
      "buy peptides online",
      "research peptides supplier",
      "peptide supplier discount",
      "semaglutide research peptides",
      "CJC-1295 research peptides",
      "ipamorelin research peptides",
      "GHK-Cu peptide",
      "retatrutide research peptides",
      "peptides sale online",
      "best peptide supplier discount",
      "peptide research compounds sale",
    ],
  },

  ascensionPeptides: {
    title: "Ascension Peptides Discount Code | Research Peptides Sale & Deals | Refer Labs",
    description:
      "Find the latest Ascension Peptides discount codes and peptides sale offers. Save on high-purity research peptides for hormone signalling, metabolic, and anti-aging studies. Access the current deal via our referral link.",
    url: `${SITE_URL}/ascensionpeptides`,
    keywords: [
      "ascension peptides discount code",
      "ascension peptides promo code",
      "ascension peptides sale",
      "ascension peptides review",
      "ascension peptides reddit",
      "peptides sale",
      "research peptides sale",
      "research peptide deals",
      "peptide research compounds",
      "peptide supplier sale",
      "buy peptides online",
      "peptide supplier discount",
      "research peptides online",
      "lab grade peptides sale",
      "peptides sale online",
      "research peptides discount code",
      "peptide supplier deals",
    ],
  },

  bioPeptiTech: {
    title: "BioPeptiTech Discount Code | Peptides Sale & Research Peptides Deals | Refer Labs",
    description:
      "Find the latest BioPeptiTech discount codes and peptides sale offers. Compare research peptide deals and save on lab-grade peptide compounds for longevity, metabolic, and hormone signalling research.",
    url: `${SITE_URL}/biopeptitech`,
    keywords: [
      "biopeptitech discount code",
      "biopeptitech promo code",
      "biopeptitech sale",
      "biopeptitech review",
      "biopeptitech reddit",
      "peptides sale",
      "research peptides sale",
      "peptide discount code",
      "buy peptides online",
      "peptide supplier discounts",
      "peptide research compounds sale",
      "research peptides discount code",
      "peptide supplier deals",
      "peptides sale online",
      "best peptide supplier discount",
      "longevity research peptides",
      "metabolic research peptides",
    ],
  },

  bestPeptideSupplier: {
    title: "Best Peptide Supplier 2026: Apollo, Ascension & BioPeptiTech Compared | Refer Labs",
    description:
      "Compare the best research peptide suppliers in 2026 — Apollo Peptide Sciences, Ascension Peptides, and BioPeptiTech. Current discount codes, peptides sale offers, purity standards, and catalogue coverage. For research use only.",
    url: `${SITE_URL}/best-peptide-supplier`,
    keywords: [
      "best peptide supplier 2026",
      "best research peptide supplier",
      "peptides sale",
      "research peptides comparison",
      "peptide discount code",
      "buy peptides online",
      "peptide supplier review",
      "apollo peptide sciences review",
      "ascension peptides review",
      "biopeptitech review",
      "research peptide suppliers reddit",
      "peptide supplier comparison",
      "lab grade peptides",
      "best peptide supplier reddit",
      "peptide suppliers australia",
      "apollo vs ascension peptides",
      "peptide supplier discount",
      "research peptides deals",
      "top peptide suppliers",
      "peptide purity coa",
    ],
  },

  bestWeightLossTelehealth: {
    title: "Best Weight Loss Telehealth Australia 2026: Moshy vs Juniper vs Better Being | Refer Labs",
    description:
      "The best weight loss telehealth in Australia for 2026, compared: Moshy, Juniper and Better Being. How eligibility works, what each program costs, and how to pick the right online option for you.",
    url: `${SITE_URL}/best-weight-loss-telehealth-australia`,
    keywords: [
      "best weight loss telehealth australia 2026",
      "best weight loss telehealth australia",
      "moshy vs juniper",
      "moshy vs juniper australia",
      "moshy vs juniper vs better being",
      "online weight loss australia 2026",
      "weight loss telehealth australia",
      "GLP-1 telehealth australia",
      "semaglutide telehealth australia",
      "moshy weight loss review",
      "juniper weight loss review",
      "better being australia",
      "australian weight loss program comparison",
      "best online weight management australia",
      "weight loss program australia 2026",
      "weight loss medication telehealth australia",
      "telehealth weight loss reddit australia",
      "moshy vs juniper reddit",
    ],
  },

  moshyVsJuniper: {
    title: "Moshy vs Juniper 2026: Which Weight Loss Telehealth Is Right for You? | Refer Labs",
    description:
      "Moshy vs Juniper compared for 2026. Moshy runs a lean clinical pathway open to anyone eligible, Juniper wraps coaching around medication and markets to women. GLP-1 access, eligibility, cost model, coaching, and the Reddit verdict. Find which Australian weight-loss telehealth fits you.",
    url: `${SITE_URL}/moshy-vs-juniper`,
    keywords: [
      "moshy vs juniper",
      "moshy vs juniper 2026",
      "moshy vs juniper australia",
      "moshy vs juniper reddit",
      "moshy or juniper",
      "juniper vs moshy weight loss",
      "moshy weight loss australia",
      "juniper weight loss australia",
      "best glp-1 telehealth australia",
      "semaglutide telehealth australia",
      "weight loss telehealth australia 2026",
      "moshy review",
      "juniper review",
      "moshy men weight loss",
      "juniper women weight loss",
    ],
  },

  moshyVsPilot: {
    title: "Moshy vs Pilot 2026: Weight Loss Telehealth Compared (Price & Model) | Refer Labs",
    description:
      "Moshy vs Pilot compared for 2026. Moshy is gender-neutral and open to anyone eligible; Pilot is Eucalyptus's men-focused telehealth in a broader health ecosystem. How the pricing models differ, who each suits, the online process, what's included, and GLP-1 access. Information only, not medical advice.",
    url: `${SITE_URL}/moshy-vs-pilot`,
    keywords: [
      "moshy vs pilot",
      "moshy vs pilot 2026",
      "moshy vs pilot australia",
      "pilot vs moshy",
      "moshy or pilot",
      "pilot weight loss australia",
      "pilot eucalyptus weight loss",
      "moshy weight loss australia",
      "mens weight loss telehealth australia",
      "weight loss telehealth australia 2026",
      "cheapest weight loss telehealth australia",
      "glp-1 telehealth australia",
      "semaglutide telehealth australia",
      "moshy review",
      "pilot review australia",
    ],
  },

  cheapestWeightLossTelehealth: {
    title: "Cheapest Weight Loss Telehealth Australia 2026: Affordable Options Compared | Refer Labs",
    description:
      "What the cheapest weight loss telehealth in Australia really means. How subscription and pay-as-you-go pricing models differ across Moshy, Juniper, Pilot and pay-per-consult alternatives, with pricing confirmed in the consult rather than fixed figures. Why cheapest is not always the best fit. Information only, not medical advice.",
    url: `${SITE_URL}/cheapest-weight-loss-telehealth-australia`,
    keywords: [
      "cheapest weight loss telehealth australia",
      "affordable weight loss telehealth australia",
      "cheapest weight loss program australia",
      "affordable weight loss program australia",
      "cheap weight loss telehealth australia",
      "low cost weight loss telehealth australia",
      "cheapest glp-1 telehealth australia",
      "cheapest online weight loss australia",
      "weight loss telehealth cost comparison australia",
      "moshy vs juniper vs pilot price",
      "budget weight loss telehealth australia",
      "weight loss telehealth pricing australia 2026",
      "pay as you go weight loss doctor australia",
      "cheapest semaglutide telehealth australia",
    ],
  },

  moshyReview: {
    title: "Moshy Review Australia 2026: How the Service Actually Works | Refer Labs",
    description:
      "An independent Moshy review for Australians. What the clinically-led weight-loss telehealth service is, how the sign-up runs in practice, what the subscription involves, and who it suits. Information only, not medical advice.",
    url: `${SITE_URL}/moshy-review`,
    keywords: [
      "moshy review",
      "moshy review australia",
      "moshy reviews",
      "moshy review 2026",
      "is moshy any good",
      "moshy weight loss review",
      "moshy telehealth review",
      "how does moshy work",
      "moshy experience",
      "moshy honest review",
    ],
  },

  moshyEligibility: {
    title: "Moshy Eligibility Check Explained: What the Quiz Asks & What Happens Next | Refer Labs",
    description:
      "What the Moshy eligibility check actually involves. The questions the online quiz asks, how long it takes, what the practitioner review looks at, and why some applications are declined. Information only.",
    url: `${SITE_URL}/moshy-eligibility`,
    keywords: [
      "moshy eligibility",
      "moshy eligibility check",
      "moshy eligibility quiz",
      "moshy questionnaire",
      "moshy quiz",
      "moshy sign up process",
      "how to join moshy",
      "moshy application",
      "moshy eligibility criteria",
    ],
  },

  getMoshy: {
    title: "getmoshy.com.au: Is It the Official Moshy Site & the Fastest Way to Start | Refer Labs",
    description:
      "getmoshy.com.au is the official website of Moshy, the Australian telehealth weight-management service. What the site is, how the referral link works, and where the eligibility check lives.",
    url: `${SITE_URL}/getmoshy`,
    keywords: [
      "getmoshy",
      "get moshy",
      "getmoshy com au",
      "getmoshy.com.au",
      "getmoshy australia",
      "getmoshy eligibility",
      "moshy official website",
      "moshy website",
      "getmoshy legit",
    ],
  },

  weightLossTelehealthMen: {
    title: "Weight Loss Telehealth for Men in Australia 2026 | Refer Labs",
    description:
      "How weight-loss telehealth works for men in Australia. Why some services market to men, what to check before signing up with any provider, and where Moshy fits as a clinical pathway open to anyone eligible. Information only, not medical advice.",
    url: `${SITE_URL}/weight-loss-telehealth-men-australia`,
    keywords: [
      "weight loss telehealth men australia",
      "mens weight loss program online australia",
      "male weight loss telehealth",
      "online weight loss for men australia",
      "mens weight loss clinic online",
      "weight loss program for men australia",
      "male weight loss program online",
      "telehealth weight loss men",
    ],
  },

  onlineWeightLossPrograms: {
    title: "Online Weight Loss Programs Australia 2026: Medical Telehealth vs Coaching Apps | Refer Labs",
    description:
      "The three types of online weight loss programs available in Australia, how medical telehealth differs from coaching apps and meal plans, and how the main providers split up. Information only, not medical advice.",
    url: `${SITE_URL}/online-weight-loss-programs-australia`,
    keywords: [
      "online weight loss programs australia",
      "online weight loss clinic australia",
      "weight loss program online",
      "medical weight loss online australia",
      "telehealth weight loss program australia",
      "best online weight loss program australia",
      "digital weight loss program",
      "weight loss subscription australia",
    ],
  },

  moshyVsGp: {
    title: "Moshy vs Your GP for Weight Management: A Practical Comparison | Refer Labs",
    description:
      "Moshy and a regular GP are two doors to the same kind of care. How each pathway runs, where telehealth saves time, where a GP is clearly the right call, and why both are valid. Information only, not medical advice.",
    url: `${SITE_URL}/moshy-vs-gp`,
    keywords: [
      "moshy vs gp",
      "moshy or gp",
      "telehealth vs gp weight loss",
      "online clinic vs gp australia",
      "gp weight loss australia",
      "telehealth or doctor weight loss",
      "weight loss doctor online vs in person",
    ],
  },

  mensHealthTelehealth: {
    title: "Men's Health Telehealth in Australia 2026: How Online Clinics Work | Refer Labs",
    description:
      "How men's health telehealth works in Australia, what online clinics can and cannot do, how prescriptions are handled, and the main providers including Moshy and Mosh. Information only, not medical advice.",
    url: `${SITE_URL}/mens-health-telehealth-australia`,
    keywords: [
      "mens health telehealth australia",
      "online mens health clinic australia",
      "mens telehealth",
      "mens health online australia",
      "telehealth for men",
      "moshy mens health",
      "mosh mens health",
      "online doctor for men australia",
    ],
  },

  moshyAlternatives: {
    title: "Moshy Alternatives in Australia 2026: Who Else Does This? | Refer Labs",
    description:
      "The realistic alternatives to Moshy in Australia: Juniper for women, Better Being for a lifestyle-first approach, and your own GP. What each pathway offers and how they differ. Information only, not medical advice.",
    url: `${SITE_URL}/moshy-alternatives`,
    keywords: [
      "moshy alternatives",
      "alternatives to moshy",
      "apps like moshy",
      "moshy competitors",
      "services like moshy australia",
      "juniper alternative for men",
      "weight loss telehealth alternatives australia",
    ],
  },

  weightLossInjections: {
    title: "Weight Loss Injections Australia 2026: How They Work & How to Access Online | Refer Labs",
    description:
      "A plain-English guide to weight-loss injections in Australia. What GLP-1 weight-loss injections are as a category, why they are prescription-only, and how online telehealth assessment and access works. Information only, not medical advice.",
    url: `${SITE_URL}/weight-loss-injections-australia`,
    keywords: [
      "weight loss injections australia",
      "weight loss injection australia",
      "weight loss injections online australia",
      "prescription weight loss injections australia",
      "glp-1 injections australia",
      "weight loss injection cost australia",
      "how to get weight loss injections australia",
      "weight loss injections telehealth australia",
      "online weight loss injections australia",
    ],
  },

  glp1WeightLoss: {
    title: "GLP-1 Weight Loss Australia 2026: What GLP-1 Medications Are & How Access Works | Refer Labs",
    description:
      "An independent, factual guide to GLP-1 weight-loss medications in Australia. What the GLP-1 class is, why it is prescription-only, how telehealth assessment works, and why eligibility is decided by a practitioner. Information only, not medical advice.",
    url: `${SITE_URL}/glp-1-weight-loss-australia`,
    keywords: [
      "glp-1 weight loss australia",
      "glp-1 australia",
      "glp1 weight loss australia",
      "glp-1 medication australia",
      "glp-1 telehealth australia",
      "glp-1 weight loss telehealth",
      "semaglutide australia",
      "tirzepatide australia",
      "glp-1 eligibility australia",
      "how to get glp-1 australia",
    ],
  },

  weightLossTelehealthCost: {
    title: "Weight Loss Telehealth Cost Australia 2026: How Online Program Pricing Works | Refer Labs",
    description:
      "How much does weight-loss telehealth cost in Australia? A clear breakdown of consult fees, subscription models, and why medication is usually billed separately. What drives the price and how to check the current figure. Information only, not medical advice.",
    url: `${SITE_URL}/weight-loss-telehealth-cost-australia`,
    keywords: [
      "weight loss telehealth cost australia",
      "how much does weight loss telehealth cost",
      "moshy cost",
      "moshy cost australia",
      "how much does moshy cost",
      "weight loss program cost australia",
      "online weight loss cost australia",
      "weight loss injection cost australia",
      "glp-1 cost australia",
      "weight loss telehealth pricing australia",
    ],
  },

  onlineWeightLossDoctor: {
    title: "Online Weight Loss Doctor Australia 2026: How a Telehealth Consult Works | Refer Labs",
    description:
      "How seeing a weight-loss doctor online works in Australia. The eligibility questionnaire model, what a registered practitioner reviews, and how a weight-loss prescription online is handled. Information only, not medical advice.",
    url: `${SITE_URL}/online-weight-loss-doctor-australia`,
    keywords: [
      "online weight loss doctor australia",
      "weight loss prescription online australia",
      "weight loss doctor online australia",
      "online doctor weight loss australia",
      "weight loss practitioner online australia",
      "telehealth weight loss doctor australia",
      "online weight loss consultation australia",
      "weight loss prescription australia online",
      "get weight loss prescription online australia",
    ],
  },

  carrdVsDurable: {
    title: "Carrd vs Durable AI 2026: Which Website Builder Should You Use? | Refer Labs",
    description:
      "Carrd vs Durable AI compared for 2026 — Carrd is the cheapest one-page builder; Durable AI generates a full business site with CRM in 30 seconds. Pricing, AI, free plans, and which to pick.",
    url: `${SITE_URL}/carrd-vs-durable`,
    keywords: [
      "carrd vs durable",
      "carrd vs durable ai",
      "carrd vs durable 2026",
      "durable vs carrd",
      "best cheap website builder 2026",
      "ai website builder vs carrd",
      "carrd alternative",
      "durable ai alternative",
      "one page website builder vs ai website builder",
      "cheapest website builder 2026",
    ],
  },

  durableVsButternut: {
    title: "Durable AI vs Butternut AI (2026): Which AI Website Builder Wins? | Refer Labs",
    description:
      "Durable AI vs Butternut AI compared for 2026. Durable generates a business site in 30 seconds with a built-in CRM and invoicing; Butternut builds a full multi-page site from one prompt in about 20 seconds. Setup speed, free tiers, what you get, pricing, and which to pick.",
    url: `${SITE_URL}/durable-vs-butternut`,
    keywords: [
      "durable vs butternut",
      "durable ai vs butternut ai",
      "durable vs butternut 2026",
      "butternut vs durable",
      "butternut ai vs durable ai",
      "best ai website builder 2026",
      "durable ai review",
      "butternut ai review",
      "ai website builder comparison",
      "durable ai alternative",
      "butternut ai alternative",
      "ai website generator comparison",
    ],
  },

  apolloVsAscension: {
    title: "Apollo Peptides vs Ascension Peptides (2026): Research Supplier Comparison | Refer Labs",
    description:
      "Apollo Peptides vs Ascension Peptides compared for 2026 on the supplier dimensions that matter: catalogue range, third-party testing and COA documentation, shipping, and community trust. Products are for laboratory research use only and not for human consumption. Information only.",
    url: `${SITE_URL}/apollo-vs-ascension`,
    keywords: [
      "apollo vs ascension",
      "apollo peptides vs ascension peptides",
      "apollo vs ascension peptides",
      "ascension vs apollo peptides",
      "apollo peptide sciences vs ascension peptides",
      "research peptide supplier comparison",
      "best research peptide supplier",
      "apollo peptides review",
      "ascension peptides review",
      "peptide supplier comparison 2026",
      "research peptides australia",
      "compare peptide suppliers",
    ],
  },

  carrdVsButternut: {
    title: "Carrd vs Butternut AI 2026: Simple Builder or AI Site Generator? | Refer Labs",
    description:
      "Carrd vs Butternut AI compared for 2026. Carrd is a simple one-page website builder with a free plan and Pro from $9/year; Butternut AI generates a full multi-page site from one prompt in about 20 seconds. Free tiers, what you get, pricing, and which to pick.",
    url: `${SITE_URL}/carrd-vs-butternut`,
    keywords: [
      "carrd vs butternut",
      "carrd vs butternut ai",
      "carrd vs butternut 2026",
      "butternut vs carrd",
      "butternut ai vs carrd",
      "one page website builder vs ai website builder",
      "carrd review",
      "butternut ai review",
      "carrd alternative",
      "butternut ai alternative",
      "cheapest website builder 2026",
      "best ai website builder 2026",
    ],
  },

  apolloVsBioPeptiTech: {
    title: "Apollo Peptides vs BioPeptiTech (2026): Research Supplier Comparison | Refer Labs",
    description:
      "Apollo Peptides vs BioPeptiTech compared for 2026 on the supplier dimensions that matter: catalogue range, third-party testing and COA documentation, sale frequency, and community trust. Products are for laboratory research use only and not for human consumption. Information only.",
    url: `${SITE_URL}/apollo-vs-biopeptitech`,
    keywords: [
      "apollo vs biopeptitech",
      "apollo peptides vs biopeptitech",
      "biopeptitech vs apollo peptides",
      "apollo peptide sciences vs biopeptitech",
      "research peptide supplier comparison",
      "best research peptide supplier",
      "apollo peptides review",
      "biopeptitech review",
      "peptide supplier comparison 2026",
      "research peptides australia",
      "compare peptide suppliers",
      "cheapest research peptide supplier",
    ],
  },

  ascensionVsBioPeptiTech: {
    title: "Ascension Peptides vs BioPeptiTech (2026): Research Supplier Comparison | Refer Labs",
    description:
      "Ascension Peptides vs BioPeptiTech compared for 2026 on the supplier dimensions that matter: purity and COA documentation, catalogue range, sale frequency, and community trust. Products are for laboratory research use only and not for human consumption. Information only.",
    url: `${SITE_URL}/ascension-vs-biopeptitech`,
    keywords: [
      "ascension vs biopeptitech",
      "ascension peptides vs biopeptitech",
      "biopeptitech vs ascension peptides",
      "research peptide supplier comparison",
      "best research peptide supplier",
      "ascension peptides review",
      "biopeptitech review",
      "peptide supplier comparison 2026",
      "research peptides australia",
      "compare peptide suppliers",
      "high purity research peptides",
      "cheapest research peptide supplier",
    ],
  },

  moshVsDense: {
    title: "Mosh vs Dense: Hair Loss Treatment Compared (2026) | Refer Labs",
    description:
      "Mosh vs Dense compared for 2026. Mosh is Australian prescription telehealth that can prescribe finasteride and minoxidil after a practitioner review; Dense is a non-prescription topical hair-care range. They serve different needs, clinical versus topical. Information only, not medical advice.",
    url: `${SITE_URL}/mosh-vs-dense`,
    keywords: [
      "mosh vs dense",
      "mosh vs dense hair",
      "mosh vs dense 2026",
      "dense vs mosh",
      "mosh hair vs dense hair experts",
      "hair loss treatment australia comparison",
      "prescription vs topical hair loss treatment",
      "mosh hair review",
      "dense hair experts review",
      "best hair loss treatment australia",
      "finasteride telehealth australia",
      "topical hair loss products australia",
    ],
  },

  moshVsPilot: {
    title: "Mosh vs Pilot 2026: Hair Loss & Men's Health Telehealth Compared",
    description:
      "Mosh vs Pilot compared for 2026. Both are Australian men's telehealth brands that can prescribe finasteride and minoxidil for hair loss after a practitioner review. How they differ on model, range and process, who each suits, and how to start. Information only, not medical advice.",
    url: `${SITE_URL}/mosh-vs-pilot`,
    keywords: [
      "mosh vs pilot",
      "mosh vs pilot hair loss",
      "pilot vs mosh",
      "mosh vs pilot 2026",
      "mosh or pilot hair loss",
      "mosh vs pilot finasteride",
      "mens hair loss telehealth australia",
      "finasteride minoxidil telehealth australia",
      "best hair loss treatment australia",
      "mosh hair review",
      "pilot hair loss australia",
      "online hair loss treatment australia",
    ],
  },

  juniperAlternatives: {
    title: "Juniper Alternatives 2026: Weight Loss Telehealth Options in Australia",
    description:
      "The realistic Juniper alternatives in Australia for 2026. Juniper is a coaching-led weight program that markets to women; if you want a gender-neutral option, a leaner clinical pathway, or a different price model, here are the alternatives and who each suits. Information only, not medical advice.",
    url: `${SITE_URL}/juniper-alternatives`,
    keywords: [
      "juniper alternatives",
      "juniper alternatives australia",
      "alternatives to juniper weight loss",
      "is juniper only for women",
      "juniper for men",
      "juniper vs moshy",
      "moshy vs juniper",
      "youly vs juniper",
      "weight loss telehealth australia",
      "gender neutral weight loss telehealth australia",
      "juniper weight loss review",
      "best weight loss telehealth australia",
    ],
  },

  affiliateEarningsCalculator: {
    title: "Affiliate Marketing Earnings Calculator: What Could You Make?",
    description:
      "Estimate what your audience could earn from affiliate marketing. Set audience size, channel and niche, see an honest range with every assumption shown, then find programs that fit.",
    url: `${SITE_URL}/affiliate-earnings-calculator`,
    keywords: [
      "affiliate marketing earnings calculator",
      "affiliate income calculator",
      "how much can you make affiliate marketing",
      "affiliate marketing calculator australia",
      "affiliate commission calculator",
      "affiliate revenue estimate",
      "how much do affiliates earn",
      "affiliate marketing income australia",
    ],
  },

  weightLossCostCalculator: {
    title: "Weight Loss Telehealth Cost Calculator Australia: Find Your Pathway",
    description:
      "Work out what weight-loss telehealth will cost you in Australia: compare subscription, coaching and GP pathways, what you actually pay for, and where your exact price is shown before you commit.",
    url: `${SITE_URL}/weight-loss-cost-calculator`,
    keywords: [
      "weight loss telehealth cost calculator",
      "weight loss cost calculator australia",
      "how much does weight loss telehealth cost",
      "moshy cost",
      "weight loss program cost australia",
      "weight loss subscription vs gp cost",
      "telehealth weight loss price australia",
      "weight loss pathway comparison australia",
    ],
  },

  polymarketHub: {
    title: "Polymarket: How to Sign Up & Trade Prediction Markets (2026)",
    description:
      "Your starting point for Polymarket: what it is, how to sign up on the US or international platform, how prediction markets work, fees, and guides to trading and bots.",
    url: `${SITE_URL}/polymarket`,
    keywords: [
      "polymarket",
      "polymarket 2026",
      "how to use polymarket",
      "polymarket sign up",
      "what is polymarket",
      "polymarket prediction markets",
      "polymarket guide",
      "is polymarket legit",
      "polymarket us vs international",
      "how does polymarket work",
    ],
  },

  polymarketMarkets: {
    title: "Polymarket Markets Explained: How Prediction Markets Work",
    description:
      "How Polymarket works: shares priced $0 to $1 as implied probability, Yes/No and multi-outcome markets, the CLOB order book, fees, and UMA oracle resolution.",
    url: `${SITE_URL}/polymarket/markets-explained`,
    type: "article" as const,
    keywords: [
      "polymarket markets explained",
      "how does polymarket work",
      "what is a prediction market",
      "polymarket order book clob",
      "polymarket fees",
      "polymarket uma oracle resolution",
      "yes no shares prediction market",
      "polymarket categorical markets",
      "prediction market implied probability",
      "polymarket 2026",
    ],
  },

  polymarketRegister: {
    title: "How to Register on Polymarket: Accounts, Wallets & Requirements",
    description:
      "How to sign up for Polymarket US (KYC, USD) or International (crypto wallet, USDC). Eligibility, deposit methods, custody, and referral attribution explained.",
    url: `${SITE_URL}/polymarket/how-to-register`,
    type: "article" as const,
    keywords: [
      "how to register on polymarket",
      "polymarket sign up",
      "polymarket us kyc",
      "polymarket wallet setup",
      "polymarket usdc deposit",
      "is polymarket available in my state",
      "polymarket international vs us",
      "how to fund polymarket",
      "polymarket account requirements",
      "do i need crypto for polymarket",
    ],
  },

  polymarketProfitCalculator: {
    title: "Polymarket Profit Calculator: Payout, Return & Edge (2026)",
    description:
      "Work out Polymarket profit before you trade: enter a stake and share price to see payout if it wins, max loss, return, implied probability, and your edge vs the market.",
    url: `${SITE_URL}/polymarket/profit-calculator`,
    type: "article" as const,
    keywords: [
      "polymarket profit calculator",
      "polymarket calculator",
      "polymarket payout calculator",
      "prediction market profit calculator",
      "polymarket return calculator",
      "polymarket odds to probability",
      "how to calculate polymarket profit",
      "polymarket edge calculator",
    ],
  },

  aiSalesToolsQuiz: {
    title: "Which AI Sales Tool Do You Need? 60-Second Match | Refer Labs",
    description:
      "Answer one or two quick questions and see which AI sales tool fits your bottleneck, FullEnrich, Reply.io, AiSDR or GoHighLevel, with an honest reason why.",
    url: `${SITE_URL}/ai-sales-tools-quiz`,
    keywords: [
      "which ai sales tool should i use",
      "best ai sales tool for me",
      "aisdr vs reply.io",
      "ai sdr vs sales engagement",
      "gohighlevel vs reply",
      "ai sales tool recommendation",
    ],
  },

  weightLossQuiz: {
    title: "Which Weight-Loss Option Fits You? 60-Second Match | Refer Labs",
    description:
      "Answer two quick questions and see which weight-loss route fits you, an online telehealth program or an in-person GP, with an honest reason why. Information only, not medical advice.",
    url: `${SITE_URL}/weight-loss-quiz`,
    keywords: [
      "which weight loss program is right for me",
      "weight loss telehealth or gp",
      "best weight loss option australia",
      "online weight loss program quiz",
      "how to choose a weight loss program",
      "moshy eligibility",
    ],
  },

  websiteBuilderQuiz: {
    title: "Which Website Builder Is Right for You? 60-Second Quiz",
    description:
      "Answer three quick questions and get the website builder that fits your project, Carrd, Durable AI, Butternut AI or Swipe Pages, with an honest reason why.",
    url: `${SITE_URL}/website-builder-quiz`,
    keywords: [
      "which website builder should i use",
      "website builder quiz",
      "best website builder for me",
      "carrd vs durable vs butternut",
      "website builder recommendation",
      "how to choose a website builder",
    ],
  },

  polymarketProfitableBots: {
    title: "Profitable Polymarket Trading Bots: 4 Strategies That Work",
    description:
      "Four Polymarket bot strategies where a real edge can exist: sports models, politics and correlation, market making for spread and rewards, and mispricing arbitrage.",
    url: `${SITE_URL}/polymarket/profitable-trading-bots`,
    type: "article" as const,
    keywords: [
      "profitable polymarket bots",
      "polymarket trading bot strategy",
      "polymarket market making bot",
      "polymarket arbitrage bot",
      "polymarket sports trading bot",
      "polymarket politics trading",
      "best polymarket bot strategy 2026",
      "how to make money polymarket bot",
      "automated polymarket trading strategy",
      "polymarket liquidity rewards bot",
    ],
  },

  polymarketBots: {
    title: "How to Build a Trading Bot for Polymarket (2026 Guide)",
    description:
      "Build a Polymarket trading bot: the CLOB API, py-clob-client, order signing, a market-making loop, hosting, monitoring, and the risk controls you need.",
    url: `${SITE_URL}/polymarket/trading-bots`,
    type: "article" as const,
    keywords: [
      "polymarket trading bot",
      "polymarket api",
      "py-clob-client",
      "clob-client polymarket",
      "polymarket market making bot",
      "polymarket arbitrage bot",
      "how to automate polymarket trading",
      "polymarket clob api tutorial",
      "prediction market trading bot 2026",
      "polymarket liquidity rewards bot",
    ],
  },

  polymarketEdge: {
    title: "How to Find and Measure Edge on Polymarket",
    description:
      "Where edge on Polymarket really comes from: research, maker rebates and liquidity rewards, arbitrage, plus fees, markout analysis and bankroll sizing.",
    url: `${SITE_URL}/polymarket/optimising-edge`,
    type: "article" as const,
    keywords: [
      "polymarket edge",
      "how to be profitable on polymarket",
      "prediction market trading strategy",
      "polymarket maker rebates liquidity rewards",
      "polymarket arbitrage kalshi",
      "polymarket taker fee",
      "markout analysis prediction markets",
      "kelly criterion prediction markets",
      "polymarket trading edge 2026",
      "measuring trading edge",
    ],
  },

  comparisonWebsite: {
    title: "Australia's Curated Health & Performance Comparison Platform | Refer Labs",
    description:
      "A properly researched comparison platform across five health and performance categories in Australia — ED, weight loss, hair loss, testosterone, and supplements. Not a pay-to-rank directory.",
    url: `${SITE_URL}/comparison-website`,
    keywords: [
      "best ED clinics Australia",
      "best weight loss programs Australia",
      "hair loss treatment Australia",
      "TRT clinic Australia",
      "testosterone clinic Australia",
      "Australian health comparison",
      "supplements Australia comparison",
      "men's health Australia",
      "health platform Australia",
      "performance health Australia",
    ],
  },

  bestNewsletterPlatform: {
    title: "beehiiv vs Substack vs ConvertKit 2026: Best Newsletter Platform",
    description:
      "beehiiv vs Substack vs ConvertKit (Kit) for 2026: free plans, monetisation, growth tools and pricing compared side by side, plus a clear pick for creators, writers and businesses.",
    url: `${SITE_URL}/best-newsletter-platform`,
    keywords: [
      "best newsletter platform 2026",
      "best newsletter platform",
      "beehiiv vs substack 2026",
      "beehiiv vs substack vs convertkit",
      "newsletter platform comparison 2026",
      "newsletter platform reddit 2026",
      "newsletter platform reddit",
      "substack alternative 2026",
      "best email newsletter platform",
      "newsletter monetization platform 2026",
      "grow newsletter 2026",
      "beehiiv review 2026",
      "substack vs convertkit",
      "newsletter platform free plan",
      "best platform for newsletter creators",
    ],
  },

  goHighLevel: {
    title: "GoHighLevel Review 2026: All-in-One CRM & Marketing Platform | Refer Labs",
    description:
      "GoHighLevel review 2026: the AI-powered all-in-one platform combining CRM, marketing automation, funnels and sales pipelines. Best for agencies and SMBs. From around $97/month at the time of writing, 14-day free trial. Verify current pricing on the provider.",
    url: `${SITE_URL}/gohighlevel`,
    keywords: [
      "gohighlevel review 2026",
      "gohighlevel review",
      "gohighlevel australia",
      "gohighlevel pricing 2026",
      "gohighlevel free trial",
      "gohighlevel for agencies",
      "gohighlevel crm",
      "gohighlevel vs competitors",
      "all in one marketing platform 2026",
      "ai crm platform 2026",
      "marketing automation software 2026",
      "gohighlevel reddit",
      "gohighlevel alternatives 2026",
      "best crm for agencies 2026",
      "gohighlevel starter unlimited plan",
    ],
  },

  aisdr: {
    title: "AiSDR Review 2026: The AI Sales Development Rep for B2B Outbound | Refer Labs",
    description:
      "AiSDR review: the AI SDR tool that automates B2B outbound. It finds prospects, personalises outreach across email, LinkedIn and phone, and books meetings. Integrates with HubSpot and Salesforce. From around $900/month billed quarterly at the time of writing. Verify current pricing.",
    url: `${SITE_URL}/aisdr`,
    keywords: [
      "aisdr review",
      "aisdr review 2026",
      "ai sdr tool",
      "ai sales development rep",
      "aisdr pricing",
      "aisdr vs competitors",
      "ai outbound sales tool 2026",
      "b2b outbound automation 2026",
      "ai sales rep software",
      "automate cold outreach ai",
      "ai sdr hubspot salesforce",
      "aisdr reddit",
      "best ai sdr 2026",
      "book meetings with ai",
      "ai prospecting tool 2026",
    ],
  },

  replyio: {
    title: "Reply.io Review 2026: AI Sales Engagement & Multichannel Outreach | Refer Labs",
    description:
      "Reply.io review: the AI-first sales engagement platform for multichannel outbound. Sequences across email, LinkedIn, calls and SMS, AI SDR agents, built-in B2B data, email finder and inbox warm-up. Integrates with HubSpot, Salesforce and Pipedrive. Per-user plans with a free trial. Verify current pricing.",
    url: `${SITE_URL}/replyio`,
    keywords: [
      "reply.io review",
      "reply.io review 2026",
      "reply io sales engagement",
      "reply.io pricing",
      "multichannel sales outreach tool",
      "ai sales engagement platform 2026",
      "email sequence software 2026",
      "reply.io vs aisdr",
      "reply.io alternatives",
      "cold email automation tool",
      "ai sdr agent software",
      "reply.io hubspot salesforce pipedrive",
      "reply.io reddit",
      "best sales engagement platform 2026",
      "linkedin email outreach automation",
    ],
  },

  fullenrich: {
    title: "FullEnrich Review 2026: Waterfall B2B Contact Enrichment (Email & Mobile) | Refer Labs",
    description:
      "FullEnrich review: waterfall B2B contact enrichment that queries 15+ data sources to find verified emails and mobile phone numbers. Bulk enrichment from CSV or CRM, integrates with HubSpot, Clay, Zapier and LinkedIn. Credit-based pricing with free credits to start. Verify current pricing.",
    url: `${SITE_URL}/fullenrich`,
    keywords: [
      "fullenrich review",
      "fullenrich review 2026",
      "waterfall enrichment",
      "fullenrich pricing",
      "b2b contact enrichment tool",
      "email and phone number finder 2026",
      "find mobile numbers b2b",
      "fullenrich vs clay",
      "fullenrich alternatives",
      "lead enrichment software 2026",
      "waterfall enrichment tool",
      "fullenrich hubspot clay integration",
      "b2b data enrichment 2026",
      "best contact enrichment tool 2026",
      "sales prospecting data tool",
    ],
  },

  brevo: {
    title: "Brevo Review 2026: All-in-One Email Marketing, SMS & CRM",
    description:
      "Brevo review: the all-in-one platform for email marketing, SMS, automation and a sales CRM, priced by emails sent, not list size. Free plan; who it suits and how pricing works. Verify current pricing.",
    url: `${SITE_URL}/brevo`,
    keywords: [
      "brevo review",
      "brevo review 2026",
      "brevo email marketing",
      "sendinblue brevo",
      "brevo pricing",
      "brevo vs mailchimp",
      "all in one email marketing platform",
      "email sms crm platform",
      "brevo free plan",
      "email marketing automation tool 2026",
    ],
  },

  alidrop: {
    title: "AliDrop Review 2026: AliExpress & Temu Dropshipping Tool",
    description:
      "AliDrop review: the dropshipping tool for sourcing from AliExpress, Alibaba and Temu, importing to Shopify and automating fulfilment. What it does, who it suits, and an honest take on dropshipping.",
    url: `${SITE_URL}/alidrop`,
    keywords: [
      "alidrop review",
      "alidrop review 2026",
      "alidrop dropshipping",
      "aliexpress dropshipping tool",
      "temu dropshipping",
      "alidrop pricing",
      "shopify dropshipping app",
      "best dropshipping tool 2026",
      "alidrop vs dsers",
      "dropshipping fulfilment automation",
    ],
  },

  leadpages: {
    title: "Leadpages Review 2026: Landing Page Builder for Lead Gen",
    description:
      "Leadpages review: a landing-page builder focused on lead generation, with a big template library, built-in A/B testing and lead capture. Who it suits vs a general website builder. Verify current pricing.",
    url: `${SITE_URL}/leadpages`,
    keywords: [
      "leadpages review",
      "leadpages review 2026",
      "leadpages pricing",
      "landing page builder lead generation",
      "leadpages vs clickfunnels",
      "leadpages vs swipe pages",
      "best landing page builder 2026",
      "ab testing landing pages",
      "lead capture page builder",
      "conversion landing page tool",
    ],
  },

  superfiliate: {
    title: "Superfiliate Review 2026: Affiliate & Creator Platform for Brands",
    description:
      "Superfiliate review: a creator-led growth platform for brands to run affiliate, referral and creator programs, with personalised pages per partner. For brands, not affiliates. Pricing quoted per brand.",
    url: `${SITE_URL}/superfiliate`,
    keywords: [
      "superfiliate review",
      "superfiliate review 2026",
      "superfiliate pricing",
      "affiliate program platform for brands",
      "creator affiliate platform",
      "referral program software ecommerce",
      "shopify affiliate program app",
      "creator led growth platform",
      "superfiliate vs refersion",
      "brand affiliate software 2026",
    ],
  },

  employmentHero: {
    title: "Employment Hero Review Australia 2026: HR & Payroll Software | Refer Labs",
    description:
      "Employment Hero review Australia: the Australian-built all-in-one HR, payroll and employment platform. ATO-certified Single Touch Payroll (STP Phase 2), AI recruitment, employee benefits and an employee app. Fair Work compliant. Pricing is quoted per business, not published publicly.",
    url: `${SITE_URL}/employmenthero`,
    keywords: [
      "employment hero review australia",
      "employment hero review",
      "hr software australia",
      "payroll software australia",
      "employment hero pricing",
      "employment hero australia",
      "single touch payroll software australia",
      "stp phase 2 software",
      "hr and payroll platform australia",
      "best hr software australia 2026",
      "small business payroll australia",
      "fair work compliant hr software",
      "employment hero reddit",
      "employment hero alternatives",
      "all in one hr payroll australia",
    ],
  },

  bestAiSalesTools: {
    title: "Best AI Sales Tools 2026: GoHighLevel, AiSDR, Reply.io & FullEnrich | Refer Labs",
    description:
      "The best AI sales and automation tools in 2026 compared: GoHighLevel (all-in-one CRM), AiSDR (AI outbound SDR), Reply.io (multichannel sales engagement) and FullEnrich (waterfall contact enrichment). What each is best for, pricing at the time of writing, and how to choose.",
    url: `${SITE_URL}/best-ai-sales-tools`,
    keywords: [
      "best ai sales tools 2026",
      "best ai sales tools",
      "ai sales automation tools 2026",
      "gohighlevel vs aisdr",
      "ai sales tools comparison 2026",
      "best ai crm 2026",
      "ai outbound sales tools",
      "ai sdr tools 2026",
      "sales automation software 2026",
      "ai tools for sales teams",
      "best ai tools for sales 2026",
      "ai lead generation tools 2026",
      "ai sales tools reddit",
      "ai sales stack 2026",
    ],
  },

  bestHairLossTreatmentAustralia: {
    title: "Best Hair Loss Treatment Australia 2026: Mosh vs Dense vs Telehealth Options | Refer Labs",
    description:
      "The best hair loss treatments in Australia for 2026, compared: Mosh, Dense Hair Experts and online telehealth. Finasteride and minoxidil vs topical options, real pricing, and how to actually start.",
    url: `${SITE_URL}/best-hair-loss-treatment-australia`,
    keywords: [
      "best hair loss treatment australia 2026",
      "best hair loss treatment australia",
      "mosh hair loss review australia",
      "dense hair experts review",
      "hair loss telehealth australia 2026",
      "finasteride australia telehealth",
      "minoxidil australia review",
      "hair loss treatment australia reddit",
      "mosh vs dense australia",
      "australian hair loss comparison",
      "hair loss clinic australia",
      "hair thinning treatment australia",
      "hair loss treatment reddit australia",
      "best hair loss products australia 2026",
    ],
  },

  guides: {
    title: "Guides & Comparisons | Refer Labs",
    description:
      "Honest comparison guides covering health providers, website builders, newsletter platforms, peptide suppliers, and business tools — Australia and global.",
    url: `${SITE_URL}/guides`,
    keywords: [
      "comparison guides australia",
      "product comparison reviews",
      "best health tools australia",
      "affiliate product reviews",
      "independent product comparisons",
    ],
  },

  // Secondary pages
  roiCalculator: {
    title: "Australia Expansion Estimator - ROI Calculator",
    description: "Estimate the ROI of entering Australia with Refer Labs. Model your 90-day pilot returns by industry, deal size, and engagement scope.",
    url: `${SITE_URL}/roi-calculator`,
    keywords: [
      "Australia expansion ROI",
      "market entry calculator",
      "Australia GTM ROI",
      "expansion cost estimator",
    ],
  },

  leadHacking: {
    noIndex: true,
    title: "Partner Sourcing & Activation for Australia",
    description: "We systematically source, qualify, and activate Australian partners - agencies, LinkedIn creators, and advisors - to build your distribution channel.",
    url: `${SITE_URL}/lead-hacking`,
    keywords: [
      "Australia partner sourcing",
      "Australian agency partners",
      "partner activation Australia",
      "distribution partner sourcing",
    ],
  },

  partnerProgram: {
    noIndex: true,
    title: "Partner Program - Become a Refer Labs partner",
    description: "Join the Refer Labs partner program and earn recurring revenue.",
    url: `${SITE_URL}/our-affiliate-program`,
  },

  linkedinInfluencer: {
    noIndex: true,
    title: "LinkedIn Creator Partnerships for Australia Market Entry",
    description: "Partner with verified Australian LinkedIn creators to build credibility, generate leads, and accelerate your market entry. Full-service partnership management.",
    url: `${SITE_URL}/linkedin-growth`,
    keywords: [
      "LinkedIn creator partnerships Australia",
      "Australian LinkedIn influencers",
      "B2B creator marketing Australia",
      "LinkedIn market entry Australia",
    ],
  },

  linkedinInfluencerCreator: {
    title: "Join as an Australian LinkedIn Creator",
    description: "Help overseas companies enter Australia and earn performance-based commissions. Join our curated pool of Australian LinkedIn creators.",
    url: `${SITE_URL}/linkedin-growth/influencer`,
    keywords: [
      "LinkedIn creator program Australia",
      "Australian creator partnerships",
      "earn from LinkedIn Australia",
    ],
  },

  linkedinInfluencerBusiness: {
    title: "Launch Australian Creator Campaigns for Market Entry",
    description: "Launch performance-based LinkedIn creator campaigns to build awareness and generate leads in the Australian market.",
    url: `${SITE_URL}/linkedin-growth/business`,
    keywords: [
      "Australian creator campaigns",
      "LinkedIn marketing Australia",
      "creator partnerships market entry",
    ],
  },

  financialAdvisorsService: {
    noIndex: true,
    title: "Services for Financial Advisors",
    description: "Partner programs for financial advisors and planners.",
    url: `${SITE_URL}/services/financial-advisors`,
  },

  accountantsService: {
    noIndex: true,
    title: "Services for Accountants",
    description: "Partner programs for accounting firms.",
    url: `${SITE_URL}/services/accountants`,
  },

  consultantsCoachesService: {
    noIndex: true,
    title: "Services for Consultants & Coaches",
    description: "Partner programs for consultants and coaches.",
    url: `${SITE_URL}/services/consultants-coaches`,
  },

  recruitersStaffingService: {
    noIndex: true,
    title: "Services for Recruiters & Staffing",
    description: "Partner programs for recruiters and staffing firms.",
    url: `${SITE_URL}/services/recruiters-staffing`,
  },

  insuranceBrokersService: {
    noIndex: true,
    title: "Services for Insurance Brokers",
    description: "Partner programs for insurance brokers.",
    url: `${SITE_URL}/services/insurance-brokers`,
  },

  referralPartnerships: {
    noIndex: true,
    title: "Referral & Affiliate Partnerships - Build Your Australian Partner Channel",
    description:
      "We source, activate, and manage referral and affiliate partners across Australia. Agencies, consultants, creators, and strategic allies - all tracked and managed end-to-end.",
    url: `${SITE_URL}/referral-partnerships`,
    keywords: [
      "referral partnerships Australia",
      "affiliate channel Australia",
      "partner program management",
      "Australian referral partners",
      "distribution activation Australia",
    ],
  },

  affiliatePartnerships: {
    noIndex: true,
    title: "Services - Sales Representation, Partnerships & Distribution Deals",
    description:
      "Three core services: Sales Representation, Partnership Development, and Distribution Deals for overseas companies entering Australia.",
    url: `${SITE_URL}/services`,
    keywords: [
      "Australia sales services",
      "Australian partnership services",
    ],
  },

  referralBlueprint: {
    title: "Referral Growth Blueprint: Affiliate Program List & Strategy Australia | Refer Labs",
    description:
      "Refer Labs' in-house referral marketing blueprint: a 250+ affiliate program list for Australia plus a personalised referral growth strategy written by our team. $799 AUD, delivered in 48 hours.",
    url: `${SITE_URL}/referral-blueprint`,
    keywords: [
      "referral marketing blueprint",
      "affiliate program list australia",
      "referral growth strategy",
      "affiliate program database australia",
      "best affiliate programs australia 2026",
      "affiliate marketing blueprint australia",
      "how to start affiliate marketing australia",
      "referral program list australia",
      "affiliate income blueprint",
      "affiliate marketing starter pack",
      "best recurring affiliate programs australia",
      "build affiliate business from scratch",
      "affiliate marketing side hustle australia",
      "passive income affiliate programs",
      "affiliate program database excel",
      "affiliate marketing strategy plan",
      "referral marketing business plan",
      "saas affiliate programs list",
      "high commission affiliate programs australia",
      "affiliate programs health australia",
      "affiliate programs fintech australia",
      "referral growth blueprint",
      "affiliate niche selection guide",
      "seo affiliate marketing australia",
    ],
  },

  affiliateProgramsAustralia: {
    title: "Best Affiliate Programs in Australia (2026)",
    description:
      "A practical roundup of the best affiliate programs for Australians in 2026, across SaaS, web hosting, finance, health, creator tools, retail and courses. Commission structures, cookie windows, and the networks that run them, plus how to join.",
    url: `${SITE_URL}/affiliate-programs-australia`,
    keywords: [
      "affiliate programs australia",
      "best affiliate programs australia",
      "best affiliate programs australia 2026",
      "affiliate programs australia 2026",
      "affiliate marketing programs australia",
      "commission factory programs",
      "australian affiliate networks",
      "saas affiliate programs australia",
      "high paying affiliate programs australia",
      "how to join affiliate programs australia",
      "affiliate program list australia",
    ],
  },

  highPayingAffiliatePrograms: {
    title: "Highest Paying Affiliate Programs 2026 (High-Commission Niches)",
    description:
      "The highest paying affiliate programs in 2026, focused on high-commission niches, SaaS, web hosting, finance and online courses. Twelve high-payout programs with typical commission structures and the networks that run them.",
    url: `${SITE_URL}/high-paying-affiliate-programs`,
    keywords: [
      "highest paying affiliate programs 2026",
      "high paying affiliate programs",
      "high commission affiliate programs",
      "highest paying affiliate programs",
      "best high ticket affiliate programs 2026",
      "high paying affiliate programs australia",
      "saas affiliate programs high commission",
      "web hosting affiliate programs high payout",
      "finance affiliate programs",
      "online course affiliate programs",
    ],
  },

  recurringAffiliatePrograms: {
    title: "Best Recurring Commission Affiliate Programs 2026",
    description:
      "The best recurring commission affiliate programs for 2026, subscription and SaaS programs that pay you every month a customer stays. Twelve recurring-revenue programs with typical commission structures and how they pay.",
    url: `${SITE_URL}/recurring-affiliate-programs`,
    keywords: [
      "best recurring commission affiliate programs",
      "recurring affiliate programs",
      "recurring commission affiliate programs 2026",
      "monthly recurring affiliate programs",
      "subscription affiliate programs",
      "saas recurring affiliate programs",
      "lifetime recurring affiliate programs",
      "passive income affiliate programs",
      "recurring affiliate programs australia",
    ],
  },

  howToStartAffiliateMarketingAustralia: {
    title: "How to Start Affiliate Marketing in Australia (2026 Beginner Guide)",
    description:
      "A step-by-step beginner guide to starting affiliate marketing in Australia in 2026. Choose a niche, pick programs, build a platform, disclose properly, keep the ATO in mind, and drive traffic. General information, not financial or tax advice.",
    url: `${SITE_URL}/how-to-start-affiliate-marketing-australia`,
    keywords: [
      "how to start affiliate marketing australia",
      "affiliate marketing australia for beginners",
      "start affiliate marketing australia 2026",
      "affiliate marketing beginners guide australia",
      "how to become an affiliate marketer australia",
      "affiliate marketing side hustle australia",
      "affiliate marketing tax australia",
      "affiliate marketing niche selection",
      "make money affiliate marketing australia",
    ],
  },

  dashboard: {
    title: "Dashboard",
    description: "Manage your program, track performance, and view reporting.",
    url: `${SITE_URL}/dashboard`,
    noIndex: true,
  },

  login: {
    title: "Login - Access your dashboard",
    description: "Log in to your Refer Labs account to manage your program and track progress.",
    url: `${SITE_URL}/login`,
    noIndex: true,
  },
};
