import type { HimsPageContent } from "../types";
import { FACTS_CHECKED_ON } from "../config";

export const vsMosh: HimsPageContent = {
  slug: "hims-vs-mosh",
  vertical: "weight",
  kind: "versus",
  seoTitle: "Hims vs Mosh (Pilot vs Mosh): Weight, Hair and ED Compared",
  metaDescription:
    "Hims, formerly Pilot, against Mosh for Australian men: consults, commitment, refunds, guarantees, support and delivery for weight loss, hair loss and ED.",
  eyebrow: "Men's telehealth comparison · Australia",
  h1: "Hims vs Mosh: which is better for weight loss, hair loss and ED?",
  standfirst:
    "Hims, the service formerly called Pilot, and Mosh both run weight loss, hair loss and ED programs for Australian men, starting from a free quiz and a practitioner consult. Choose Hims for 24-hour access to a care team and a phone consult. Choose Mosh to see prices before the consult, start weight loss on a three-month minimum, and consult by text, video or phone. On hair loss both offer a 180-day money-back guarantee.",
  hub: { label: "Men's health", href: "/mens-health" },
  verdictQuestion: "Is Hims or Mosh better?",
  verdict: [
    "For weight loss, the deciding difference is commitment. Hims' advertised starting offer runs twelve months, pay-upfront. Mosh's intro offer carries a three-month minimum.",
    "For hair loss, both offer a 180-day money-back guarantee and free delivery. Mosh publishes its hair prices; Hims shows them after the consult.",
    "For ED, Mosh publishes its price and lets you consult by text. Hims consults by phone, has no lock-in contract, and the Refer Labs code makes the consult free for new patients.",
  ],
  otherPartnersOnPage: ["Mosh"],
  blocks: [
    {
      type: "compare",
      id: "overview",
      heading: "Hims vs Mosh at a glance",
      intro: `Read on each provider's own website on ${FACTS_CHECKED_ON}. Offers change, so confirm at checkout.`,
      columns: ["", "Hims", "Mosh"],
      rows: [
        { label: "Background", cells: ["Formerly Pilot. Part of the Hims & Hers group.", "Australian men's health service. Its brands include Moshy."] },
        { label: "Programs for men", cells: ["Weight loss, hair loss, ED and more", "Weight loss, hair loss, ED, mental health and more"] },
        { label: "How you start", cells: ["Free quiz, then a phone consult", "Free quiz, then a consult by call, video or text"] },
        { label: "Consult", cells: ["Fee refunded if not eligible or you don't proceed. Free with the Refer Labs code.", "Free consultation to start"], verify: true },
        { label: "Prices", cells: ["Shown after the consult for hair and ED", "Published on Mosh's pricing page"] },
        { label: "Delivery", cells: ["Free, discreet, tracked", "Free, discreet"] },
        { label: "Ongoing support", cells: ["Unlimited practitioner check-ins, 24-hour Care Team", "Unlimited consultations; paid dietitian sessions for weight"] },
        { label: "Price match", cells: ["Not advertised", "Yes, on substantially comparable products, subject to an eligibility check"] },
      ],
    },
    { type: "offer", id: "offer", vertical: "weight" },
    {
      type: "compare",
      id: "weight",
      heading: "Hims vs Mosh for weight loss",
      intro: "The biggest difference between the two is how long you commit for.",
      columns: ["", "Hims", "Mosh"],
      rows: [
        { label: "Commitment on the advertised offer", cells: ["Twelve months, pay-upfront", "Minimum three months on the intro offer"] },
        { label: "Refund", cells: ["Full refund within 30 days of starting. Terms apply.", "Check Mosh's terms before you pay"], verify: true },
        { label: "Cancelling", cells: ["Hims' page says you can change or cancel at any time", "Check Mosh's terms before you pay"], verify: true },
        { label: "Extra support", cells: ["24-hour Care Team including nurses, pharmacists and clinicians", "Dietitian add-on: one-hour live sessions, paid per session"] },
      ],
      footnote: "Both providers attach their advertised weight loss offer to a minimum commitment. Ask each one for the total cost over the period you expect to stay.",
    },
    {
      type: "prose",
      id: "weight-read",
      heading: "Should I choose Hims or Mosh for weight loss?",
      paragraphs: [
        "Hims' advertised offer sits on a twelve-month pay-upfront option. Mosh's intro offer comes with a three-month minimum. If you're confident you want a year-long program, the Hims structure gives you a known total. If you want to see how a program fits first, the shorter minimum is easier to live with.",
        "Hims' page also says you can change or cancel at any time. Ask on the consult how that applies to the option you choose, and whether a monthly payment option is available.",
        "Mosh's dietitian sessions help if you want structured help with food. Hims offers round-the-clock access to its care team. Which matters more depends on whether you want scheduled coaching or someone to ask when a question comes up.",
      ],
    },
    {
      type: "compare",
      id: "hair",
      heading: "Hims vs Mosh for hair loss",
      columns: ["", "Hims", "Mosh"],
      rows: [
        { label: "Prices", cells: ["Not published; shown after the consult", "Published on Mosh's pricing page"] },
        { label: "Plan structure", cells: ["Keep and Regrow, with 2-in-1, 3-in-1 and single-action options", "Prevention, Prevention & Regrowth and an advanced plan, from 85+ variations"] },
        { label: "Money-back guarantee", cells: ["180 days. Terms apply.", "180 days on hair subscriptions. Terms apply."] },
        { label: "Deliveries", cells: ["Every two or three months", "Subscription; frequency set with your plan"], verify: true },
        { label: "Cancelling", cells: ["Before the next order, no fee", "Check Mosh's terms"], verify: true },
      ],
      footnote: "Hims runs a public new-patient hair offer from time to time. Offers can't be combined, so compare at checkout.",
    },
    {
      type: "compare",
      id: "ed",
      heading: "Hims vs Mosh for ED",
      columns: ["", "Hims", "Mosh"],
      rows: [
        { label: "Prices", cells: ["Not published; shown after the consult", "Published on Mosh's pricing page"] },
        { label: "Plans", cells: ["ED Stamina, ED Performance and a combined plan", "Tailored plan with your choice of delivery frequency"] },
        { label: "Consult", cells: ["Phone. Fee refunded if not eligible; free with the Refer Labs code.", "Call, video or text"] },
        { label: "Contract", cells: ["No lock-in; pause or cancel any time", "Check Mosh's terms"], verify: true },
        { label: "Packaging", cells: ["Discreet, unmarked", "Discreet"] },
      ],
    },
    {
      type: "picks",
      id: "picks",
      heading: "Hims or Mosh: which suits your situation?",
      picks: [
        { label: "You want to see prices before any consult", pick: "Mosh", why: "Mosh publishes its prices for hair, weight and ED. Hims shows hair and ED prices after the consult." },
        { label: "You want the shortest weight loss commitment to start", pick: "Mosh", why: "Mosh's intro weight offer carries a three-month minimum, against twelve months on Hims' advertised pay-upfront option." },
        { label: "You want help available at any hour", pick: "Hims", why: "Hims includes round-the-clock access to a care team of nurses, pharmacists and clinicians, plus unlimited practitioner check-ins." },
        { label: "You want structured help with food", pick: "Mosh", why: "Mosh offers one-hour dietitian sessions as a paid add-on to its weight program." },
        { label: "You'd rather talk than type", pick: "Either", why: "Hims consults are by phone. Mosh offers calls as well as video and text." },
        { label: "You want a long hair guarantee", pick: "Either", why: "Both offer 180 days on hair plans. Read each provider's terms." },
        { label: "Free consult for ED", pick: "Hims with the Refer Labs code", why: "Hims charges a consult fee. The Refer Labs code makes it free for new patients." },
      ],
    },
    {
      type: "prose",
      id: "method",
      heading: "How we compared Hims and Mosh",
      paragraphs: [
        `We read each provider's public pages, pricing and FAQs on ${FACTS_CHECKED_ON}, and compared only what a customer can check before signing up: how you start, commitment, refund and cancellation terms, support and delivery. Where a provider doesn't publish something, we say so.`,
        "We don't compare what the practitioners supply, because Australian advertising law doesn't allow it to be named publicly and because it depends on your assessment.",
        "Refer Labs is paid by both Hims and Mosh when a new customer signs up using our code or link. The two pay us different amounts.",
      ],
    },
    {
      type: "faq",
      id: "faq",
      heading: "Hims vs Mosh: common questions",
      items: [
        { q: "Is Mosh or Pilot better?", a: "Pilot is now Hims: pilot.com.au says Pilot has joined the Hims & Hers group and sends new patients to the Hims quiz. So the comparison today is Hims vs Mosh. Hims suits men who want 24-hour care team access and a phone consult; Mosh suits men who want to see prices first and a shorter weight loss minimum." },
        { q: "Is Hims cheaper than Mosh?", a: "It depends on the program and how long you stay. Mosh publishes its prices on its pricing page; Hims shows hair and ED prices after the consult. For weight loss, compare the total over each provider's minimum commitment: twelve months on Hims' advertised pay-upfront option, three months on Mosh's intro offer." },
        { q: "Do Hims and Mosh both have a money-back guarantee?", a: "Both offer a 180-day money-back guarantee on hair plans, subject to their terms. Hims also offers a full refund within 30 days of starting its weight loss program." },
        { q: "Which has better support, Hims or Mosh?", a: "Hims includes 24-hour access to its care team and unlimited practitioner check-ins. Mosh includes unlimited consultations and offers paid dietitian sessions for weight loss. Pick based on the kind of help you want." },
        { q: "Can I switch from Mosh to Hims, or the other way?", a: "Yes. You start as a new patient with the quiz and consult. Tell the new practitioner about any plan you're currently on so they can assess you properly." },
      ],
    },
  ],
  sources: [
    { label: "Hims: Weight loss", url: "https://hims.com.au/weight-loss" },
    { label: "Hims: Hair loss", url: "https://hims.com.au/hair-loss" },
    { label: "Hims: Erectile dysfunction", url: "https://hims.com.au/erectile-dysfunction" },
    { label: "Pilot: notice that Pilot has joined the Hims & Hers group", url: "https://pilot.com.au/" },
    { label: "Mosh: Pricing", url: "https://www.getmosh.com.au/pricing" },
    { label: "Mosh: Weight loss", url: "https://www.getmosh.com.au/weight-loss" },
    { label: "Mosh: Hair loss", url: "https://www.getmosh.com.au/hair-loss" },
  ],
  related: [
    { label: "Hims weight loss", href: "/hims", desc: "How the program works, the commitment and the refund window." },
    { label: "Hims hair loss", href: "/hims-hair-loss", desc: "Keep and Regrow plans and the 180-day money-back guarantee." },
    { label: "Hims ED treatment", href: "/hims-ed", desc: "The three ED plans, the phone consult and cancelling." },
    { label: "Best men's weight loss program in Australia", href: "/best-mens-weight-loss-program-australia", desc: "Hims, Mosh and an in-person practitioner, side by side." },
  ],
};
