import {
  CARRD_URL, DURABLE_URL, BUTTERNUT_URL, SWIPE_PAGES_URL, BEEHIIV_URL,
  GOHIGHLEVEL_URL, AISDR_URL, REPLY_IO_URL, FULLENRICH_URL, SNOV_URL, NUTSHELL_URL,
  APOLLO_URL, ASCENSION_URL, BIOPEPTITECH_URL,
  EMPLOYMENT_HERO_URL, GUSTO_URL, PAYONEER_URL,
  CLOUDTALK_URL, KRISPCALL_URL, DEXT_URL, TRAINUAL_URL, LINDY_URL, ELEVENLABS_URL,
  LEADPAGES_URL, HELLOBAR_URL, OUTGROW_URL, FLEXIQUIZ_URL,
  PIPEDRIVE_URL, ZOOMINFO_URL, ACTIVECAMPAIGN_URL, MELIO_URL,
  LANDINGI_URL, MEETGEEK_URL,
  KEAP_URL, CAPSULE_URL, BEAUTIFULAI_URL,
} from "@/lib/affiliate-links";

/**
 * Programmatic category catalog.
 *
 * Each Vertical here becomes a fully-rendered category hub at /compare/<slug>,
 * generated by a single dynamic route. Adding a new category to Australia's
 * comparison platform is data entry — add a Vertical below and the page,
 * metadata, sitemap entry and internal links appear automatically.
 *
 * This is the scaling mechanism behind the "hundreds of industries" vision.
 */

export type Provider = {
  name: string;
  /** One-line "best for" positioning */
  bestFor: string;
  blurb: string;
  facts: { label: string; value: string }[];
  /** Outbound affiliate link (tracked). Omit for non-affiliate reference. */
  affiliateUrl?: string;
  externalUrl?: string;
  /** Internal review/brand page, if one exists. */
  reviewHref?: string;
  ctaLabel: string;
  /** true => primary green button; false => outline */
  featured?: boolean;
};

export type Vertical = {
  slug: string;
  eyebrow: string;
  h1Lead: string;
  h1Accent: string;
  intro: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  /** Optional info/compliance note shown near the top. */
  note?: string;
  roundupHref?: { href: string; label: string };
  /** search-index category for the auto-generated related-guides block. */
  relatedCategory?: string;
  providers: Provider[];
  faqs: { q: string; a: string }[];
};

export const CATALOG: Vertical[] = [
  {
    slug: "website-builders",
    eyebrow: "Software",
    h1Lead: "Website & landing-page builders in Australia:",
    h1Accent: "the shortlist",
    intro:
      "From a free one-page site to an AI-generated business website in thirty seconds, plus dedicated landing-page builders for campaigns. This hub sorts them by what they are actually for, so you pick the right tool the first time.",
    metaTitle: "Best Website & Landing Page Builders 2026: Carrd, Durable AI, Butternut, Leadpages & More | Refer Labs",
    metaDescription:
      "Compare website and landing-page builders for 2026: Carrd for cheap one-page sites, Durable AI and Butternut AI for instant AI-built sites, Swipe Pages and Leadpages for high-converting landing pages. Independent, no pay-to-rank.",
    keywords: [
      "best website builder 2026",
      "website builder comparison",
      "ai website builder australia",
      "cheapest website builder",
      "best landing page builder",
      "leadpages vs landingi",
      "compare website builders",
    ],
    roundupHref: { href: "/best-website-builder", label: "Read the full head-to-head comparison" },
    relatedCategory: "Software",
    providers: [
      {
        name: "Carrd",
        bestFor: "Cheapest one-page sites",
        blurb: "The best value in simple websites. Free to start, Pro from US$9/year. Ideal for a portfolio, link-in-bio, or a single landing page.",
        facts: [
          { label: "Price", value: "Free; Pro from US$9/year" },
          { label: "Best for", value: "One-page sites" },
          { label: "AI build", value: "No" },
        ],
        affiliateUrl: CARRD_URL,
        reviewHref: "/carrd",
        ctaLabel: "Try Carrd free",
        featured: true,
      },
      {
        name: "Durable AI",
        bestFor: "AI-built business sites",
        blurb: "Generates a full multi-page business website in about 30 seconds, with a CRM and invoicing built in. Best for service businesses that want a working site fast.",
        facts: [
          { label: "Price", value: "Monthly subscription" },
          { label: "Best for", value: "Service businesses" },
          { label: "AI build", value: "Yes, ~30s" },
        ],
        affiliateUrl: DURABLE_URL,
        reviewHref: "/durableai",
        ctaLabel: "Try Durable AI",
      },
      {
        name: "Butternut AI",
        bestFor: "Instant full-site drafts",
        blurb: "Generates a complete multi-page site from a single prompt in about 20 seconds. Best treated as a strong first draft you then edit.",
        facts: [
          { label: "Price", value: "Free to try" },
          { label: "Best for", value: "Instant drafts" },
          { label: "AI build", value: "Yes, ~20s" },
        ],
        affiliateUrl: BUTTERNUT_URL,
        reviewHref: "/butternut",
        ctaLabel: "Try Butternut AI",
      },
      {
        name: "Swipe Pages",
        bestFor: "Paid-ad landing pages",
        blurb: "AMP landing pages that load in under a second, with A/B testing. A specialist tool for paid-ad campaigns, not a general website builder.",
        facts: [
          { label: "Price", value: "14-day free trial" },
          { label: "Best for", value: "Paid ads" },
          { label: "AI build", value: "No" },
        ],
        affiliateUrl: SWIPE_PAGES_URL,
        reviewHref: "/swipepages",
        ctaLabel: "Start the free trial",
      },
      {
        name: "Leadpages",
        bestFor: "Landing pages that convert",
        blurb: "A landing-page and lead-capture builder with a big template library, built-in A/B testing, pop-ups and alert bars. Best when your main goal is capturing leads, not just publishing a site.",
        facts: [
          { label: "Role", value: "Landing pages / lead capture" },
          { label: "Best for", value: "Marketers & small business" },
          { label: "Pricing", value: "7-day trial; from US$49 first month" },
        ],
        affiliateUrl: LEADPAGES_URL,
        reviewHref: "/leadpages",
        ctaLabel: "See Leadpages",
      },
      {
        name: "Landingi",
        bestFor: "Landing pages with A/B testing",
        blurb: "A no-code landing-page builder with a large template library, A/B testing and lead capture. A strong alternative to Leadpages for marketers running campaigns.",
        facts: [
          { label: "Role", value: "Landing pages / conversion" },
          { label: "Best for", value: "Marketers & agencies" },
          { label: "Pricing", value: "No free plan; from US$24/mo" },
        ],
        affiliateUrl: LANDINGI_URL,
        reviewHref: "/landingi",
        ctaLabel: "See Landingi",
      },
    ],
    faqs: [
      {
        q: "What is the best website builder for beginners in Australia?",
        a: "Carrd is the easiest and cheapest starting point for a simple site, and most people are live within an hour. If you want a full business site with no effort, Durable AI and Butternut AI generate one from a prompt in under 30 seconds.",
      },
      {
        q: "What is the cheapest website builder?",
        a: "Carrd, comfortably. It has a genuine free plan and Pro tiers from $19 per year. The AI builders let you generate a site free before committing to a paid publishing plan.",
      },
      {
        q: "Which builder is best for a business website?",
        a: "For a multi-page business site with light back-office tools, Durable AI is the strongest pick because it bundles a CRM and invoicing. Butternut AI is the fastest way to a full first draft you then refine.",
      },
    ],
  },
  {
    slug: "newsletter-platforms",
    eyebrow: "Creator tools",
    h1Lead: "Newsletter platforms:",
    h1Accent: "where to build your audience",
    intro:
      "Where you start an email list shapes how much you keep and how fast you grow. This hub compares the platforms on free plans, monetisation and growth tools.",
    metaTitle: "Best Newsletter Platform 2026: beehiiv vs Substack vs ConvertKit | Refer Labs",
    metaDescription:
      "Compare newsletter platforms for 2026: beehiiv for growth and monetisation, Substack for discovery, ConvertKit for automation. Free plans and revenue share compared.",
    keywords: [
      "best newsletter platform 2026",
      "beehiiv vs substack",
      "newsletter platform comparison",
      "email newsletter platform australia",
      "substack alternative",
    ],
    roundupHref: { href: "/best-newsletter-platform", label: "Read the full beehiiv vs Substack vs ConvertKit comparison" },
    relatedCategory: "Creator tools",
    providers: [
      {
        name: "beehiiv",
        bestFor: "Growth and monetisation",
        blurb: "Built for creators serious about growing and monetising a newsletter. Free up to 2,500 subscribers, with a built-in ad network, referral program and 0% cut on paid subscriptions.",
        facts: [
          { label: "Free plan", value: "Up to 2,500 subs" },
          { label: "Revenue cut", value: "0% on paid subs" },
          { label: "Best for", value: "Serious creators" },
        ],
        affiliateUrl: BEEHIIV_URL,
        reviewHref: "/beehiiv",
        ctaLabel: "Try beehiiv free",
        featured: true,
      },
      {
        name: "Substack",
        bestFor: "Simple start & discovery",
        blurb: "The simplest way to start a paid newsletter, with a strong built-in discovery network. Takes a 10% cut of paid subscription revenue, which adds up at scale.",
        facts: [
          { label: "Free plan", value: "No subscriber cap" },
          { label: "Revenue cut", value: "10% on paid" },
          { label: "Best for", value: "Beginners" },
        ],
        externalUrl: "https://substack.com",
        ctaLabel: "Visit Substack",
      },
      {
        name: "ConvertKit (Kit)",
        bestFor: "Automation & funnels",
        blurb: "A full email marketing platform with advanced automation and segmentation. Better for product businesses with complex sequences than newsletter-first creators.",
        facts: [
          { label: "Free plan", value: "Up to 1,000 subs" },
          { label: "Strength", value: "Automation" },
          { label: "Best for", value: "Product funnels" },
        ],
        externalUrl: "https://kit.com",
        ctaLabel: "Visit Kit",
      },
    ],
    faqs: [
      {
        q: "What is the best newsletter platform in 2026?",
        a: "For creators focused on growth and monetisation, beehiiv is the strongest option, with a generous free plan, built-in growth tools, and no cut on paid subscriptions. Substack is a simpler starting point with better discovery.",
      },
      {
        q: "beehiiv vs Substack: which should I choose?",
        a: "beehiiv if you are serious about growing and keeping all your revenue. Substack if you want the simplest possible start and value its discovery network, accepting the 10% cut on paid subscriptions.",
      },
    ],
  },
  {
    slug: "ai-sales-tools",
    eyebrow: "AI & sales",
    h1Lead: "AI sales tools:",
    h1Accent: "matched to your stack",
    intro:
      "These tools sit at different points in the sales stack, data, outreach, an AI rep, an all-in-one platform, and an easy CRM. This hub sorts them by the job you actually need doing, so you buy the right layer, not the loudest one.",
    metaTitle: "AI Sales Tools Compared 2026: Data, Outreach, AI SDR & CRM | Refer Labs",
    metaDescription:
      "Compare AI sales tools by role for 2026: FullEnrich and ZoomInfo for contact data, Reply.io for multichannel outreach, AiSDR for a done-for-you AI rep, and CRMs like Pipedrive, Nutshell and GoHighLevel. Independent, no pay-to-rank.",
    keywords: [
      "ai sales tools comparison",
      "best ai sales tools 2026",
      "compare ai sdr tools",
      "sales engagement platform comparison",
      "b2b sales tools australia",
    ],
    roundupHref: { href: "/best-ai-sales-tools", label: "Read the full AI sales tools roundup" },
    relatedCategory: "AI & sales",
    providers: [
      {
        name: "FullEnrich",
        bestFor: "Contact data (email + mobile)",
        blurb: "Waterfall enrichment that queries 15+ sources to find verified emails and mobile numbers. The data layer that feeds every other outbound tool.",
        facts: [
          { label: "Role", value: "Contact data" },
          { label: "Pricing", value: "Free trial (50 credits); from US$55/mo" },
          { label: "Best for", value: "Fixing bad data" },
        ],
        affiliateUrl: FULLENRICH_URL,
        reviewHref: "/fullenrich",
        ctaLabel: "See FullEnrich",
        featured: true,
      },
      {
        name: "Reply.io",
        bestFor: "Multichannel outreach you run",
        blurb: "An AI-first sales engagement platform for running your own sequences across email, LinkedIn, calls and SMS, with AI SDR agents and deliverability tools built in.",
        facts: [
          { label: "Role", value: "Sales engagement" },
          { label: "Pricing", value: "No free plan; from US$49/user/mo" },
          { label: "Best for", value: "Hands-on teams" },
        ],
        affiliateUrl: REPLY_IO_URL,
        reviewHref: "/replyio",
        ctaLabel: "See Reply.io",
      },
      {
        name: "AiSDR",
        bestFor: "A done-for-you AI rep",
        blurb: "An AI sales development rep that prospects, personalises outreach across channels and books meetings, so you build pipeline without hiring SDRs.",
        facts: [
          { label: "Role", value: "AI SDR" },
          { label: "Pricing", value: "From US$250/mo (Solo); US$900/mo Explore" },
          { label: "Best for", value: "Pipeline without hiring" },
        ],
        affiliateUrl: AISDR_URL,
        reviewHref: "/aisdr",
        ctaLabel: "See AiSDR",
      },
      {
        name: "GoHighLevel",
        bestFor: "All-in-one CRM & marketing",
        blurb: "One platform for CRM, marketing automation, funnels and follow-up, best for agencies and SMBs consolidating a stack of tools.",
        facts: [
          { label: "Role", value: "All-in-one platform" },
          { label: "Pricing", value: "From US$97/mo; Unlimited US$297/mo" },
          { label: "Best for", value: "Agencies & SMBs" },
        ],
        affiliateUrl: GOHIGHLEVEL_URL,
        reviewHref: "/gohighlevel",
        ctaLabel: "Try GoHighLevel",
      },
      {
        name: "Nutshell",
        bestFor: "An easy CRM with marketing built in",
        blurb: "A straightforward sales CRM that bundles pipeline management, email sequences, web forms and reporting, so smaller teams get a CRM and basic marketing in one without enterprise complexity.",
        facts: [
          { label: "Role", value: "Sales CRM + marketing" },
          { label: "Pricing", value: "No free plan; from US$13/user/mo" },
          { label: "Best for", value: "SMB sales teams" },
        ],
        affiliateUrl: NUTSHELL_URL,
        reviewHref: "/nutshell",
        ctaLabel: "See Nutshell",
      },
      {
        name: "Pipedrive",
        bestFor: "A visual pipeline CRM",
        blurb: "A deal-first sales CRM built around a visual pipeline you drag deals through, with activity reminders, automation and reporting. Best for teams that want a CRM reps actually keep updated.",
        facts: [
          { label: "Role", value: "Sales CRM / pipeline" },
          { label: "Best for", value: "SMB sales teams" },
          { label: "Pricing", value: "No free plan; from US$14/seat/mo" },
        ],
        affiliateUrl: PIPEDRIVE_URL,
        reviewHref: "/pipedrive",
        ctaLabel: "See Pipedrive",
      },
      {
        name: "ActiveCampaign",
        bestFor: "Email + automation + CRM",
        blurb: "Email marketing with a powerful automation builder and a light CRM, so follow-up reacts to what each contact does. Best once you have outgrown basic send-and-hope email.",
        facts: [
          { label: "Role", value: "Email / automation" },
          { label: "Best for", value: "SMBs wanting automation" },
          { label: "Pricing", value: "No free plan; from US$15/mo" },
        ],
        affiliateUrl: ACTIVECAMPAIGN_URL,
        reviewHref: "/activecampaign",
        ctaLabel: "See ActiveCampaign",
      },
      {
        name: "ZoomInfo",
        bestFor: "Enterprise B2B data",
        blurb: "An enterprise sales-intelligence platform with a large contact database, direct dials and buyer-intent signals. Best for scaled teams running outbound at volume; quote-only pricing.",
        facts: [
          { label: "Role", value: "B2B data & intent" },
          { label: "Best for", value: "Enterprise sales teams" },
          { label: "Pricing", value: "Quote-only; enterprise annual" },
        ],
        affiliateUrl: ZOOMINFO_URL,
        reviewHref: "/zoominfo",
        ctaLabel: "See ZoomInfo",
      },
      {
        name: "Snov.io",
        bestFor: "Prospecting + outreach on a budget",
        blurb: "An all-in-one prospecting platform: email finder and verifier, drip email campaigns and a light CRM. A budget-friendly way to combine finding leads and reaching them in one tool.",
        facts: [
          { label: "Role", value: "Prospecting + outreach" },
          { label: "Pricing", value: "Free trial; from US$39/mo" },
          { label: "Best for", value: "Solo & small teams" },
        ],
        affiliateUrl: SNOV_URL,
        ctaLabel: "See Snov.io",
      },
      {
        name: "Keap",
        bestFor: "CRM + automation for small business",
        blurb: "An all-in-one CRM with sales and marketing automation for small businesses: pipeline, email and SMS, and automated follow-up in one platform, so leads are chased without manual work. Pricing scales with contacts.",
        facts: [
          { label: "Role", value: "CRM + marketing automation" },
          { label: "Best for", value: "Small businesses & solopreneurs" },
          { label: "Pricing", value: "No free plan; from US$249/mo" },
        ],
        affiliateUrl: KEAP_URL,
        reviewHref: "/keap",
        ctaLabel: "See Keap",
      },
      {
        name: "Capsule",
        bestFor: "A simple CRM teams keep using",
        blurb: "An easy, lightweight CRM for small businesses: contacts, a visual sales pipeline, tasks and email tracking, without enterprise complexity. Free for up to 250 contacts and two users.",
        facts: [
          { label: "Role", value: "Simple sales CRM" },
          { label: "Best for", value: "Small teams wanting an easy CRM" },
          { label: "Pricing", value: "Free up to 250 contacts; from US$18/user/mo" },
        ],
        affiliateUrl: CAPSULE_URL,
        reviewHref: "/capsule",
        ctaLabel: "See Capsule",
      },
    ],
    faqs: [
      {
        q: "What are the best AI sales tools in 2026?",
        a: "It depends on the job. FullEnrich and ZoomInfo supply contact data, Reply.io runs your own multichannel outreach, AiSDR is a done-for-you AI rep, and CRMs like Pipedrive, Nutshell and GoHighLevel manage the pipeline and follow-up. Many teams stack more than one.",
      },
      {
        q: "Which AI sales tool should I start with?",
        a: "Start with your bottleneck. Bad contact data points to FullEnrich; not enough conversations points to Reply.io or AiSDR; scattered tools and follow-up point to GoHighLevel. Pricing is indicative, verify current figures on each provider.",
      },
    ],
  },
  {
    slug: "research-peptides",
    eyebrow: "Research use only",
    h1Lead: "Research peptide suppliers:",
    h1Accent: "purity and catalogue, compared",
    intro:
      "For laboratory research use only. This hub compares suppliers on testing documentation, catalogue depth and current offers, so researchers can source the right compound from a reputable vendor.",
    note: "All compounds referenced are for laboratory research purposes only and are not for human or veterinary use. Nothing here is medical advice.",
    metaTitle: "Research Peptide Suppliers Compared 2026: Purity & Catalogue | Refer Labs",
    metaDescription:
      "Compare research peptide suppliers for 2026: Apollo Peptide Sciences, Ascension Peptides and BioPeptiTech, on third-party testing, catalogue depth and current offers. Research use only.",
    keywords: [
      "research peptide suppliers comparison",
      "best peptide supplier 2026",
      "compare peptide vendors",
      "apollo vs ascension peptides",
      "research peptides australia",
    ],
    roundupHref: { href: "/best-peptide-supplier", label: "Read the full supplier comparison" },
    relatedCategory: "Research peptides",
    providers: [
      {
        name: "Apollo Peptide Sciences",
        bestFor: "Broadest catalogue",
        blurb: "The widest research peptide catalogue of the three, with third-party testing documentation. A strong default when you need range. For research use only.",
        facts: [
          { label: "Catalogue", value: "Broadest" },
          { label: "Testing", value: "Third-party" },
          { label: "Offer", value: "Via referral link" },
        ],
        affiliateUrl: APOLLO_URL,
        reviewHref: "/apollopeptides",
        ctaLabel: "See Apollo",
        featured: true,
      },
      {
        name: "Ascension Peptides",
        bestFor: "Purity focus",
        blurb: "High-purity, lab-grade compounds frequently referenced in researcher communities for documentation quality. For research use only.",
        facts: [
          { label: "Focus", value: "High purity" },
          { label: "Testing", value: "Documented" },
          { label: "Offer", value: "Via referral link" },
        ],
        affiliateUrl: ASCENSION_URL,
        reviewHref: "/ascensionpeptides",
        ctaLabel: "See Ascension",
      },
      {
        name: "BioPeptiTech",
        bestFor: "Frequent sales",
        blurb: "Lab-grade compounds with regular promotions, a lower-cost entry point for longevity, metabolic and hormone-signalling research. For research use only.",
        facts: [
          { label: "Value", value: "Frequent sales" },
          { label: "Coverage", value: "Longevity, metabolic" },
          { label: "Offer", value: "Regular promotions" },
        ],
        affiliateUrl: BIOPEPTITECH_URL,
        reviewHref: "/biopeptitech",
        ctaLabel: "See BioPeptiTech",
      },
    ],
    faqs: [
      {
        q: "What is the best research peptide supplier in 2026?",
        a: "Apollo Peptide Sciences has the broadest catalogue, Ascension Peptides is cited for purity documentation, and BioPeptiTech runs frequent sales. The right choice depends on the compound and documentation you need. All products are for laboratory research use only.",
      },
      {
        q: "How do I get a research peptide discount?",
        a: "The most reliable route is an affiliate referral link, which applies any active offer automatically, rather than hunting for a promo code that may have expired. This hub links directly to each supplier. Research use only.",
      },
    ],
  },
  {
    slug: "hr-payroll",
    eyebrow: "HR & payroll",
    h1Lead: "HR & payroll platforms:",
    h1Accent: "pay and manage your team",
    intro:
      "Software that runs payroll, onboarding and people admin in one place. This hub compares the main platforms by who they suit and where they operate, so you pick one built for your team, not the loudest brand.",
    metaTitle: "HR & Payroll Software Compared 2026: Employment Hero vs Gusto | Refer Labs",
    metaDescription:
      "Compare HR and payroll platforms for 2026: Employment Hero for Australian and NZ teams, Gusto for US teams. Independent comparison, no pay-to-rank.",
    keywords: [
      "hr payroll software comparison",
      "employment hero vs gusto",
      "best payroll software 2026",
      "hr software small business",
      "online payroll platform",
    ],
    relatedCategory: "Software",
    providers: [
      {
        name: "Employment Hero",
        bestFor: "All-in-one for AU & NZ teams",
        blurb: "Australian HR, payroll and employment platform covering onboarding, payroll, benefits and compliance in one system. A common default for Australian small and mid-sized businesses.",
        facts: [
          { label: "Role", value: "HR + payroll" },
          { label: "Best for", value: "AU & NZ teams" },
          { label: "Pricing", value: "From A$10/employee/mo; enterprise on request" },
        ],
        affiliateUrl: EMPLOYMENT_HERO_URL,
        reviewHref: "/employmenthero",
        ctaLabel: "See Employment Hero",
        featured: true,
      },
      {
        name: "Gusto",
        bestFor: "Payroll & benefits for US teams",
        blurb: "US payroll, benefits and HR platform known for straightforward full-service payroll, automatic tax filing and benefits administration for small businesses. US-based teams only.",
        facts: [
          { label: "Role", value: "Payroll + benefits" },
          { label: "Availability", value: "US only" },
          { label: "Pricing", value: "From US$49/mo + US$6/person" },
        ],
        affiliateUrl: GUSTO_URL,
        ctaLabel: "See Gusto",
      },
      {
        name: "Trainual",
        bestFor: "Onboarding, training & SOPs",
        blurb: "Documents how your business runs, builds role-based onboarding and training, and keeps standard operating procedures searchable. Sits alongside payroll on the people-and-process side.",
        facts: [
          { label: "Role", value: "Training + SOPs" },
          { label: "Best for", value: "Growing & multi-site teams" },
          { label: "Pricing", value: "Custom pricing, book a demo" },
        ],
        affiliateUrl: TRAINUAL_URL,
        reviewHref: "/trainual",
        ctaLabel: "See Trainual",
      },
    ],
    faqs: [
      {
        q: "Employment Hero or Gusto, which should I use?",
        a: "It comes down to where your team is. Employment Hero is built for Australian and New Zealand businesses and handles local payroll and compliance. Gusto is a US-only platform, strong at US payroll, tax filing and benefits. Choose by your team's country rather than features alone.",
      },
      {
        q: "Is Gusto available in Australia?",
        a: "No. Gusto is a US-focused payroll and HR platform and is not built for Australian payroll or compliance. Australian businesses are better served by a local platform such as Employment Hero. We flag availability so you don't sign up for the wrong region.",
      },
      {
        q: "How much does payroll software cost in Australia?",
        a: "Most platforms charge a base fee plus a per-employee monthly rate, so the total scales with headcount and the modules you switch on (payroll only, or HR, benefits and rostering as well). Because plans and add-ons change, check the current per-employee price on the provider before you commit rather than relying on a headline figure.",
      },
      {
        q: "Can I switch payroll providers part-way through a year?",
        a: "Yes, though it is easiest at the start of a financial year or a pay cycle. You will need to migrate year-to-date pay data, employee records and any leave balances so reporting stays correct. Most platforms offer onboarding help for this; plan the cutover around a pay run so nobody is paid late.",
      },
    ],
  },
  {
    slug: "sales-outreach",
    eyebrow: "Sales & outreach",
    h1Lead: "Sales outreach tools:",
    h1Accent: "find leads and reach them",
    intro:
      "Tools for building a prospect list and running outreach across email and other channels. This is the outreach layer, distinct from a full CRM, so this hub sorts them by how hands-on you want to be and what you can spend.",
    metaTitle: "Sales Outreach Tools Compared 2026: Snov.io vs Reply.io | Refer Labs",
    metaDescription:
      "Compare sales outreach tools for 2026: Snov.io for budget prospecting plus email, Reply.io for AI-first multichannel sequences. Independent, no pay-to-rank.",
    keywords: [
      "sales outreach tools",
      "snov.io vs reply.io",
      "cold email software comparison",
      "email outreach platform",
      "sales sequence tool 2026",
    ],
    relatedCategory: "AI & sales",
    providers: [
      {
        name: "Snov.io",
        bestFor: "Prospecting + email on a budget",
        blurb: "An all-in-one prospecting platform: email finder and verifier, drip email campaigns and a light CRM. A budget-friendly way to find leads and reach them in one tool.",
        facts: [
          { label: "Role", value: "Prospecting + outreach" },
          { label: "Best for", value: "Solo & small teams" },
          { label: "Pricing", value: "Free trial; from US$39/mo" },
        ],
        affiliateUrl: SNOV_URL,
        ctaLabel: "See Snov.io",
        featured: true,
      },
      {
        name: "Reply.io",
        bestFor: "AI multichannel sequences",
        blurb: "An AI-first sales engagement platform for running multichannel sequences across email, LinkedIn, calls and SMS, with AI SDR agents and deliverability tools built in.",
        facts: [
          { label: "Role", value: "Sales engagement" },
          { label: "Best for", value: "Hands-on teams" },
          { label: "Pricing", value: "No free plan; from US$49/user/mo" },
        ],
        affiliateUrl: REPLY_IO_URL,
        reviewHref: "/replyio",
        ctaLabel: "See Reply.io",
      },
    ],
    faqs: [
      {
        q: "Snov.io or Reply.io, which fits me?",
        a: "Snov.io is the budget all-rounder that combines finding leads and emailing them, best for solo operators and small teams. Reply.io is stronger for multichannel sequences and AI agents, and suits teams running serious outbound. Start with Snov if cost matters most; move to Reply as volume grows.",
      },
      {
        q: "Do I also need a separate contact-data tool?",
        a: "If your list is thin or your data is stale, pair an outreach tool with a dedicated enrichment tool. Our AI sales tools hub covers the data layer, such as FullEnrich, that feeds these outreach platforms.",
      },
      {
        q: "Is cold email legal in Australia?",
        a: "Commercial email in Australia is governed by the Spam Act 2003. In practice that means you need consent (express or reasonably inferred from an existing business relationship), you must clearly identify who you are, and every message must include a working unsubscribe. B2B outreach to a relevant business address can qualify, but blanket unsolicited emailing does not. Reputable outreach tools include unsubscribe handling and deliverability controls to help you stay compliant, but the legal responsibility is yours.",
      },
      {
        q: "How much do sales outreach tools cost?",
        a: "Most price either per user per month or on credits for finding and verifying contacts, and several offer a free tier to start. Budget tools like Snov.io are usually the cheapest entry point; team platforms like Reply.io cost more per seat as you add channels and AI features. Check the current plan on each provider, since limits and pricing change often.",
      },
    ],
  },
  {
    slug: "payments",
    eyebrow: "Payments & finance",
    h1Lead: "Payments & finance:",
    h1Accent: "get paid, and keep the books straight",
    intro:
      "Tools for receiving payments, paying vendors and moving money internationally, plus the bookkeeping that keeps the finances tidy. Useful for freelancers, creators and online businesses working with overseas clients, marketplaces and affiliate programs.",
    metaTitle: "Payments & Finance Tools Compared 2026: Payoneer, Dext & Melio | Refer Labs",
    metaDescription:
      "Payments and finance tools for 2026: Payoneer for cross-border payments and multi-currency accounts, Dext for bookkeeping automation, and Melio for US business bill pay. Independent, no pay-to-rank.",
    keywords: [
      "payoneer review",
      "cross border payment tools",
      "get paid internationally freelancer",
      "bookkeeping automation software",
      "dext review",
      "payoneer australia",
    ],
    note: "We're building this category out. Payoneer is our first covered provider; more will be added as we review them.",
    relatedCategory: "Software",
    providers: [
      {
        name: "Payoneer",
        bestFor: "Cross-border payments & payouts",
        blurb: "A global payments platform with multi-currency business accounts, cross-border payouts, and the ability to get paid by international marketplaces and clients. Widely used by freelancers, affiliates and e-commerce sellers.",
        facts: [
          { label: "Role", value: "Global payments" },
          { label: "Best for", value: "Freelancers & online business" },
          { label: "Pricing", value: "Free to open; per-transaction fees apply" },
        ],
        affiliateUrl: PAYONEER_URL,
        ctaLabel: "See Payoneer",
        featured: true,
      },
      {
        name: "Dext",
        bestFor: "Bookkeeping automation",
        blurb: "Captures receipts, invoices and bills, extracts the data automatically and syncs it into accounting software like Xero, QuickBooks and Sage. The finance-admin layer next to payments.",
        facts: [
          { label: "Role", value: "Bookkeeping automation" },
          { label: "Best for", value: "Accountants & small business" },
          { label: "Pricing", value: "No free plan; from US$25/mo (annual)" },
        ],
        affiliateUrl: DEXT_URL,
        reviewHref: "/dext",
        ctaLabel: "See Dext",
      },
      {
        name: "Melio",
        bestFor: "Paying vendors (US businesses)",
        blurb: "B2B bill pay for US businesses: pay vendors by bank transfer, card or check and sync to QuickBooks or Xero. Free plan to start; requires a US business and US bank account to send.",
        facts: [
          { label: "Role", value: "Bill pay / accounts payable" },
          { label: "Availability", value: "US-only for senders" },
          { label: "Pricing", value: "Free plan; paid from US$25/mo" },
        ],
        affiliateUrl: MELIO_URL,
        reviewHref: "/melio",
        ctaLabel: "See Melio",
      },
    ],
    faqs: [
      {
        q: "What is Payoneer used for?",
        a: "Receiving international payments, holding balances in multiple currencies, and paying contractors or suppliers abroad. It is popular with freelancers, affiliate marketers and online sellers who get paid by overseas platforms and programs.",
      },
      {
        q: "Is Payoneer available in Australia?",
        a: "Yes. Payoneer operates globally, including Australia, and is commonly used to get paid in USD, EUR or GBP by international marketplaces and affiliate programs, then withdraw to a local account.",
      },
      {
        q: "Is Payoneer safe to use?",
        a: "Payoneer is a regulated payments provider used by millions of businesses and freelancers worldwide, with standard protections like two-factor authentication. As with any financial account, the usual care applies: enable 2FA, watch for phishing, and read the fee schedule so transfer and currency-conversion costs don't surprise you.",
      },
      {
        q: "Payoneer vs PayPal or Wise, what's the difference?",
        a: "All three move money across borders, but they lean different ways. Payoneer is strong for getting paid by international marketplaces and running a multi-currency business account; Wise is known for low-cost currency conversion on transfers; PayPal is the most widely accepted for one-off consumer payments. The best fit depends on who is paying you and in which currencies. We'll add hands-on comparisons as we expand this category.",
      },
    {
        q: "What should you look for in a cross-border payment tool?",
        a: "Five things matter most: the total cost (transfer fees plus the currency-conversion margin, which is often the bigger cost), the currencies and countries supported, how fast payouts actually land, whether you can hold a multi-currency balance, and the provider's regulation and security. Compare the all-in cost on a real transfer amount, not just the headline fee, because conversion spreads vary a lot between providers.",
      },
      {
        q: "How long do international payments take?",
        a: "It depends on the method and route. Transfers within a provider's own network or to a local account can be near-instant to a couple of business days; traditional bank wires and less common currency corridors can take longer. Always check the provider's stated timeframe for your specific currency and destination, and note that weekends and public holidays can add delay.",
      },
    ],
  },
  {
    slug: "business-phone",
    eyebrow: "Business phone",
    h1Lead: "Business phone systems:",
    h1Accent: "calls, texts and numbers in one place",
    intro:
      "Cloud phone systems let a team make and take calls from the browser and mobile, with virtual numbers instead of hardware. This hub compares the main options by who they suit, from lean remote teams to busier sales and support floors.",
    metaTitle: "Business Phone Systems Compared 2026: CloudTalk vs KrispCall | Refer Labs",
    metaDescription:
      "Compare cloud business phone systems for 2026: CloudTalk for AI call-centre features and analytics, KrispCall for virtual numbers and a shared team inbox. Independent, no pay-to-rank.",
    keywords: ["business phone system comparison", "cloudtalk vs krispcall", "best voip for business 2026", "cloud phone system", "virtual phone number for teams"],
    relatedCategory: "Software",
    providers: [
      {
        name: "CloudTalk",
        bestFor: "AI call centre for sales & support",
        blurb: "A cloud call-centre platform with smart routing, recording, analytics, SMS/WhatsApp and AI voice agents. Strongest where call volume and reporting matter.",
        facts: [
          { label: "Role", value: "Cloud call centre" },
          { label: "Best for", value: "Sales & support teams" },
          { label: "Pricing", value: "No free plan; from €19/user/mo" },
        ],
        affiliateUrl: CLOUDTALK_URL,
        reviewHref: "/cloudtalk",
        ctaLabel: "See CloudTalk",
        featured: true,
      },
      {
        name: "KrispCall",
        bestFor: "Virtual numbers & shared inbox",
        blurb: "A cloud phone system focused on getting virtual local and international numbers and running a shared team inbox. Leaner and good for remote and distributed teams.",
        facts: [
          { label: "Role", value: "Cloud phone / numbers" },
          { label: "Best for", value: "Remote & distributed teams" },
          { label: "Pricing", value: "No free plan; from US$12/user/mo (annual)" },
        ],
        affiliateUrl: KRISPCALL_URL,
        reviewHref: "/krispcall",
        ctaLabel: "See KrispCall",
      },
    ],
    faqs: [
      {
        q: "CloudTalk or KrispCall, which should I choose?",
        a: "CloudTalk leans toward call-centre features and analytics for busier sales and support teams; KrispCall leans toward simple virtual numbers and a shared inbox for smaller and remote teams. Choose by call volume and how much reporting you need. Both run in the browser and mobile with a free trial to test.",
      },
      {
        q: "Do I need a business phone system or just a mobile?",
        a: "A dedicated system is worth it once more than one person handles calls, you want a shared inbox and records, or you need numbers in more than one region. For a single person making occasional calls, a mobile or a basic plan is usually enough.",
      },
      {
        q: "How does a cloud phone system work?",
        a: "Instead of desk phones and on-site hardware, calls run over the internet through an app on your computer or mobile. You buy virtual numbers, set up routing and voicemail in a dashboard, and your team makes and takes calls from anywhere. Because it is software, adding a user or a number is a settings change rather than new equipment.",
      },
      {
        q: "Can I keep my existing phone number?",
        a: "In most cases yes. Cloud phone systems generally support number porting, moving your existing business number across to the new provider. It can take a few business days and availability depends on the number type and country, so confirm porting support and timeframes with the provider first, and keep the old service active until the port completes.",
      },
    ],
  },
  {
    slug: "ai-tools",
    eyebrow: "AI tools",
    h1Lead: "AI tools:",
    h1Accent: "assistants, voice and AI branding",
    intro:
      "AI tools now cover very different jobs, from automating your admin to generating lifelike voice or a whole brand identity. This hub sorts a growing set by what they actually do, so you pick the one that fits the task rather than the loudest launch.",
    metaTitle: "Best AI Tools Compared 2026: Lindy, ElevenLabs & Logome | Refer Labs",
    metaDescription:
      "Compare AI tools for 2026 by job: Lindy for automating inbox, scheduling and CRM work, ElevenLabs for AI voice, Logome for AI logos and branding, MeetGeek for AI meeting notes. Independent, no pay-to-rank.",
    keywords: ["best ai tools 2026", "lindy ai review", "elevenlabs review", "ai automation tools", "ai voice generator"],
    relatedCategory: "AI & sales",
    providers: [
      {
        name: "Lindy",
        bestFor: "Automating repetitive admin",
        blurb: "An AI work assistant that connects to your apps and takes over inbox triage, scheduling, follow-ups and CRM updates. Best where you have a lot of repeatable admin.",
        facts: [
          { label: "Role", value: "AI work assistant" },
          { label: "Best for", value: "Automating admin" },
          { label: "Pricing", value: "No free tier; from US$49.99/mo" },
        ],
        affiliateUrl: LINDY_URL,
        reviewHref: "/lindy",
        ctaLabel: "See Lindy",
        featured: true,
      },
      {
        name: "ElevenLabs",
        bestFor: "AI voice & text-to-speech",
        blurb: "An AI audio platform for realistic text-to-speech, voice cloning, dubbing and voice agents, with an API for developers. Start free, scale on paid plans.",
        facts: [
          { label: "Role", value: "AI voice / TTS" },
          { label: "Best for", value: "Creators & developers" },
          { label: "Pricing", value: "Free plan; paid from US$5/mo" },
        ],
        affiliateUrl: ELEVENLABS_URL,
        reviewHref: "/elevenlabs",
        ctaLabel: "See ElevenLabs",
      },
      {
        name: "MeetGeek",
        bestFor: "AI meeting notes",
        blurb: "An AI meeting assistant that auto-joins Zoom, Meet and Teams calls to record, transcribe and summarise them with action items. Best for teams that live in meetings.",
        facts: [
          { label: "Role", value: "AI meeting assistant" },
          { label: "Best for", value: "Teams in lots of calls" },
          { label: "Pricing", value: "Free plan; from US$9.99/user/mo" },
        ],
        affiliateUrl: MEETGEEK_URL,
        reviewHref: "/meetgeek",
        ctaLabel: "See MeetGeek",
      },
      {
        name: "Beautiful.ai",
        bestFor: "AI presentations",
        blurb: "Presentation software with design built in: add content and its smart templates handle the layout automatically, so decks look designed without a designer. An AI generator can draft a first-pass deck from a prompt.",
        facts: [
          { label: "Role", value: "AI presentation software" },
          { label: "Best for", value: "Founders, teams & consultants" },
          { label: "Pricing", value: "No free plan; Pro from US$12/mo" },
        ],
        affiliateUrl: BEAUTIFULAI_URL,
        reviewHref: "/beautifulai",
        ctaLabel: "See Beautiful.ai",
      },
    ],
    faqs: [
      {
        q: "Which AI tool do I actually need?",
        a: "Start from the job. If you want to automate repetitive admin like inbox, scheduling and CRM updates, an AI assistant like Lindy fits. If you need voiceover, narration or dubbing, an AI voice tool like ElevenLabs fits. They solve different problems, so match the tool to the task.",
      },
      {
        q: "Are these AI tools free to try?",
        a: "Both offer a low-risk way to start: ElevenLabs has a free plan, and Lindy offers a free trial. Free tiers and trials change, so confirm the current limits on each provider before you rely on them.",
      },
      {
        q: "AI assistant vs AI voice, what's the difference?",
        a: "An AI assistant like Lindy does work for you, automating tasks across your apps such as email, scheduling and CRM updates. An AI voice tool like ElevenLabs generates audio, turning text into natural speech, cloning voices or dubbing video. One saves you time on admin; the other produces content. Pick based on whether you need work done or audio made.",
      },
      {
        q: "Is my data safe with AI tools?",
        a: "It depends on the provider. Reputable AI tools publish how they store and use your data and whether inputs are used to train models. Before connecting sensitive accounts or uploading confidential material, read the provider's data and security terms, and prefer plans or settings that exclude your data from training where that matters to you.",
      },
    ],
  },
  {
    slug: "lead-generation",
    eyebrow: "Conversion tools",
    h1Lead: "Popups, quizzes & lead capture:",
    h1Accent: "turn attention into leads",
    intro:
      "Traffic is wasted if visitors leave without a trace. These tools capture and convert with on-site popups, interactive quizzes and calculators, and tests and assessments, sorted by how you want to turn attention into leads. For dedicated landing-page builders, see the website builders hub.",
    metaTitle: "Best Popup, Quiz & Lead-Capture Tools 2026: Hello Bar, Outgrow, FlexiQuiz | Refer Labs",
    metaDescription:
      "Compare lead-capture tools for 2026: Hello Bar for on-site popups and bars, Outgrow for interactive quizzes and calculators, FlexiQuiz for tests and assessments. Independent, no pay-to-rank.",
    keywords: ["lead capture tools", "website popup tool", "interactive content tool", "quiz maker for lead gen", "best popup tool"],
    relatedCategory: "Software",
    providers: [
      {
        name: "Hello Bar",
        bestFor: "On-site popups & bars",
        blurb: "Adds no-code popups, sticky bars and overlays to any website to capture emails and drive clicks, with targeting and A/B testing. A quick conversion win for sites that already get traffic.",
        facts: [
          { label: "Role", value: "Popups & notification bars" },
          { label: "Best for", value: "Growing an email list" },
          { label: "Pricing", value: "Free plan; paid from US$29/mo" },
        ],
        affiliateUrl: HELLOBAR_URL,
        reviewHref: "/hellobar",
        ctaLabel: "See Hello Bar",
        featured: true,
      },
      {
        name: "Outgrow",
        bestFor: "Interactive quizzes & calculators",
        blurb: "Builds no-code calculators, quizzes, assessments and polls that engage visitors and capture better-qualified leads. Best when you want people to interact and self-qualify.",
        facts: [
          { label: "Role", value: "Interactive content" },
          { label: "Best for", value: "Engagement & lead quality" },
          { label: "Pricing", value: "Free plan; paid from US$14/mo" },
        ],
        affiliateUrl: OUTGROW_URL,
        reviewHref: "/outgrow",
        ctaLabel: "See Outgrow",
      },
      {
        name: "FlexiQuiz",
        bestFor: "Tests & assessments",
        blurb: "An online quiz, test and assessment maker with automatic marking, certificates and reporting. Best when you need real assessments for training or hiring, not just a marketing quiz.",
        facts: [
          { label: "Role", value: "Quiz & test maker" },
          { label: "Best for", value: "Trainers & assessments" },
          { label: "Pricing", value: "Free plan; paid from US$17/mo" },
        ],
        affiliateUrl: FLEXIQUIZ_URL,
        reviewHref: "/flexiquiz",
        ctaLabel: "See FlexiQuiz",
      },
    ],
    faqs: [
      {
        q: "Which lead-capture tool do I need?",
        a: "Match it to how you capture. For popups and bars on your existing site, Hello Bar. For interactive quizzes and calculators that qualify leads, Outgrow. For real tests and assessments with grading, FlexiQuiz. For a dedicated landing page, see Leadpages in the website builders hub. Many sites use more than one.",
      },
      {
        q: "Are these lead-capture tools free to try?",
        a: "Mostly yes: Hello Bar, Outgrow and FlexiQuiz all have free plans. Free tiers and trials change, so confirm the current limits on each provider before you rely on them.",
      },
      {
        q: "Landing page or popup, which lifts conversions more?",
        a: "They do different jobs. A landing page is a dedicated, distraction-free page for a single offer, best for paid traffic and campaigns, and you will find those builders in the website builders hub. A popup or bar captures visitors on your existing pages before they leave. Used together they cover both.",
      },
    ],
  },
];

export function getVertical(slug: string): Vertical | undefined {
  return CATALOG.find((v) => v.slug === slug);
}
