import {
  CARRD_URL, DURABLE_URL, BUTTERNUT_URL, SWIPE_PAGES_URL, BEEHIIV_URL,
  GOHIGHLEVEL_URL, AISDR_URL, REPLY_IO_URL, FULLENRICH_URL,
  APOLLO_URL, ASCENSION_URL, BIOPEPTITECH_URL,
} from "@/lib/affiliate-links";

/**
 * Programmatic category catalog.
 *
 * Each Vertical here becomes a fully-rendered category hub at /compare/<slug>,
 * generated by a single dynamic route. Adding a new category to Australia's
 * comparison platform is data entry — add a Vertical below and the page,
 * metadata, sitemap entry and internal links appear automatically.
 *
 * This is the scaling mechanism behind the "hundreds of industries" vision.
 */

export type Provider = {
  name: string;
  /** One-line "best for" positioning */
  bestFor: string;
  blurb: string;
  facts: { label: string; value: string }[];
  /** Outbound affiliate link (tracked). Omit for non-affiliate reference. */
  affiliateUrl?: string;
  externalUrl?: string;
  /** Internal review/brand page, if one exists. */
  reviewHref?: string;
  ctaLabel: string;
  /** true => primary green button; false => outline */
  featured?: boolean;
};

export type Vertical = {
  slug: string;
  eyebrow: string;
  h1Lead: string;
  h1Accent: string;
  intro: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  /** Optional info/compliance note shown near the top. */
  note?: string;
  roundupHref?: { href: string; label: string };
  /** search-index category for the auto-generated related-guides block. */
  relatedCategory?: string;
  providers: Provider[];
  faqs: { q: string; a: string }[];
};

export const CATALOG: Vertical[] = [
  {
    slug: "website-builders",
    eyebrow: "Category hub · Software",
    h1Lead: "Website builders in Australia:",
    h1Accent: "the honest shortlist",
    intro:
      "From a free one-page site to an AI-generated business website in thirty seconds. This hub sorts the builders by what they are actually for, so you pick the right tool the first time.",
    metaTitle: "Best Website Builders 2026: Compare Carrd, Durable AI, Butternut & Swipe Pages | Refer Labs",
    metaDescription:
      "Compare website builders for 2026 — Carrd for cheap one-page sites, Durable AI and Butternut AI for instant AI-built sites, Swipe Pages for paid-ad landing pages. Independent, no pay-to-rank.",
    keywords: [
      "best website builder 2026",
      "website builder comparison",
      "ai website builder australia",
      "cheapest website builder",
      "carrd vs durable",
      "compare website builders",
    ],
    roundupHref: { href: "/best-website-builder", label: "Read the full head-to-head comparison" },
    relatedCategory: "Software",
    providers: [
      {
        name: "Carrd",
        bestFor: "Cheapest one-page sites",
        blurb: "The best value in simple websites. Free to start, Pro from about $9/year. Ideal for a portfolio, link-in-bio, or a single landing page.",
        facts: [
          { label: "Price", value: "Free; Pro from ~$9/year" },
          { label: "Best for", value: "One-page sites" },
          { label: "AI build", value: "No" },
        ],
        affiliateUrl: CARRD_URL,
        reviewHref: "/carrd",
        ctaLabel: "Try Carrd free",
        featured: true,
      },
      {
        name: "Durable AI",
        bestFor: "AI-built business sites",
        blurb: "Generates a full multi-page business website in about 30 seconds, with a CRM and invoicing built in. Best for service businesses that want a working site fast.",
        facts: [
          { label: "Price", value: "Monthly subscription" },
          { label: "Best for", value: "Service businesses" },
          { label: "AI build", value: "Yes, ~30s" },
        ],
        affiliateUrl: DURABLE_URL,
        reviewHref: "/durableai",
        ctaLabel: "Try Durable AI",
      },
      {
        name: "Butternut AI",
        bestFor: "Instant full-site drafts",
        blurb: "Generates a complete multi-page site from a single prompt in about 20 seconds. Best treated as a strong first draft you then edit.",
        facts: [
          { label: "Price", value: "Free to try" },
          { label: "Best for", value: "Instant drafts" },
          { label: "AI build", value: "Yes, ~20s" },
        ],
        affiliateUrl: BUTTERNUT_URL,
        reviewHref: "/butternut",
        ctaLabel: "Try Butternut AI",
      },
      {
        name: "Swipe Pages",
        bestFor: "Paid-ad landing pages",
        blurb: "AMP landing pages that load in under a second, with A/B testing. A specialist tool for paid-ad campaigns, not a general website builder.",
        facts: [
          { label: "Price", value: "14-day free trial" },
          { label: "Best for", value: "Paid ads" },
          { label: "AI build", value: "No" },
        ],
        affiliateUrl: SWIPE_PAGES_URL,
        reviewHref: "/swipepages",
        ctaLabel: "Start the free trial",
      },
    ],
    faqs: [
      {
        q: "What is the best website builder for beginners in Australia?",
        a: "Carrd is the easiest and cheapest starting point for a simple site, and most people are live within an hour. If you want a full business site with no effort, Durable AI and Butternut AI generate one from a prompt in under 30 seconds.",
      },
      {
        q: "What is the cheapest website builder?",
        a: "Carrd, comfortably. It has a genuine free plan and Pro tiers from around $9 per year. The AI builders let you generate a site free before committing to a paid publishing plan.",
      },
      {
        q: "Which builder is best for a business website?",
        a: "For a multi-page business site with light back-office tools, Durable AI is the strongest pick because it bundles a CRM and invoicing. Butternut AI is the fastest way to a full first draft you then refine.",
      },
    ],
  },
  {
    slug: "newsletter-platforms",
    eyebrow: "Category hub · Creator tools",
    h1Lead: "Newsletter platforms:",
    h1Accent: "where to build your audience",
    intro:
      "Where you start an email list shapes how much you keep and how fast you grow. This hub compares the platforms on free plans, monetisation and growth tools.",
    metaTitle: "Best Newsletter Platform 2026: beehiiv vs Substack vs ConvertKit | Refer Labs",
    metaDescription:
      "Compare newsletter platforms for 2026 — beehiiv for growth and monetisation, Substack for discovery, ConvertKit for automation. Free plans and revenue share compared.",
    keywords: [
      "best newsletter platform 2026",
      "beehiiv vs substack",
      "newsletter platform comparison",
      "email newsletter platform australia",
      "substack alternative",
    ],
    roundupHref: { href: "/best-newsletter-platform", label: "Read the full beehiiv vs Substack vs ConvertKit comparison" },
    relatedCategory: "Creator tools",
    providers: [
      {
        name: "beehiiv",
        bestFor: "Growth and monetisation",
        blurb: "Built for creators serious about growing and monetising a newsletter. Free up to 2,500 subscribers, with a built-in ad network, referral program and 0% cut on paid subscriptions.",
        facts: [
          { label: "Free plan", value: "Up to 2,500 subs" },
          { label: "Revenue cut", value: "0% on paid subs" },
          { label: "Best for", value: "Serious creators" },
        ],
        affiliateUrl: BEEHIIV_URL,
        reviewHref: "/beehiiv",
        ctaLabel: "Try beehiiv free",
        featured: true,
      },
      {
        name: "Substack",
        bestFor: "Simple start & discovery",
        blurb: "The simplest way to start a paid newsletter, with a strong built-in discovery network. Takes a 10% cut of paid subscription revenue, which adds up at scale.",
        facts: [
          { label: "Free plan", value: "No subscriber cap" },
          { label: "Revenue cut", value: "10% on paid" },
          { label: "Best for", value: "Beginners" },
        ],
        externalUrl: "https://substack.com",
        ctaLabel: "Visit Substack",
      },
      {
        name: "ConvertKit (Kit)",
        bestFor: "Automation & funnels",
        blurb: "A full email marketing platform with advanced automation and segmentation. Better for product businesses with complex sequences than newsletter-first creators.",
        facts: [
          { label: "Free plan", value: "Up to 1,000 subs" },
          { label: "Strength", value: "Automation" },
          { label: "Best for", value: "Product funnels" },
        ],
        externalUrl: "https://kit.com",
        ctaLabel: "Visit Kit",
      },
    ],
    faqs: [
      {
        q: "What is the best newsletter platform in 2026?",
        a: "For creators focused on growth and monetisation, beehiiv is the strongest option — a generous free plan, built-in growth tools, and no cut on paid subscriptions. Substack is a simpler starting point with better discovery.",
      },
      {
        q: "beehiiv vs Substack — which should I choose?",
        a: "beehiiv if you are serious about growing and keeping all your revenue. Substack if you want the simplest possible start and value its discovery network, accepting the 10% cut on paid subscriptions.",
      },
    ],
  },
  {
    slug: "ai-sales-tools",
    eyebrow: "Category hub · AI & sales",
    h1Lead: "AI sales tools:",
    h1Accent: "matched to your stack",
    intro:
      "These tools sit at different points in the sales stack, data, outreach, an AI rep, and an all-in-one platform. This hub sorts them by the job you actually need doing, so you buy the right layer, not the loudest one.",
    metaTitle: "AI Sales Tools Compared 2026: Data, Outreach, AI SDR & CRM | Refer Labs",
    metaDescription:
      "Compare AI sales tools by role for 2026: FullEnrich for contact data, Reply.io for multichannel outreach, AiSDR for a done-for-you AI rep, GoHighLevel for all-in-one CRM. Independent, no pay-to-rank.",
    keywords: [
      "ai sales tools comparison",
      "best ai sales tools 2026",
      "compare ai sdr tools",
      "sales engagement platform comparison",
      "b2b sales tools australia",
    ],
    roundupHref: { href: "/best-ai-sales-tools", label: "Read the full AI sales tools roundup" },
    relatedCategory: "AI & sales",
    providers: [
      {
        name: "FullEnrich",
        bestFor: "Contact data (email + mobile)",
        blurb: "Waterfall enrichment that queries 15+ sources to find verified emails and mobile numbers. The data layer that feeds every other outbound tool.",
        facts: [
          { label: "Role", value: "Contact data" },
          { label: "Pricing", value: "Credit-based, free credits (verify)" },
          { label: "Best for", value: "Fixing bad data" },
        ],
        affiliateUrl: FULLENRICH_URL,
        reviewHref: "/fullenrich",
        ctaLabel: "See FullEnrich",
        featured: true,
      },
      {
        name: "Reply.io",
        bestFor: "Multichannel outreach you run",
        blurb: "An AI-first sales engagement platform for running your own sequences across email, LinkedIn, calls and SMS, with AI SDR agents and deliverability tools built in.",
        facts: [
          { label: "Role", value: "Sales engagement" },
          { label: "Pricing", value: "Per-user, free trial (verify)" },
          { label: "Best for", value: "Hands-on teams" },
        ],
        affiliateUrl: REPLY_IO_URL,
        reviewHref: "/replyio",
        ctaLabel: "See Reply.io",
      },
      {
        name: "AiSDR",
        bestFor: "A done-for-you AI rep",
        blurb: "An AI sales development rep that prospects, personalises outreach across channels and books meetings, so you build pipeline without hiring SDRs.",
        facts: [
          { label: "Role", value: "AI SDR" },
          { label: "Pricing", value: "From ~$900/mo quarterly (verify)" },
          { label: "Best for", value: "Pipeline without hiring" },
        ],
        affiliateUrl: AISDR_URL,
        reviewHref: "/aisdr",
        ctaLabel: "See AiSDR",
      },
      {
        name: "GoHighLevel",
        bestFor: "All-in-one CRM & marketing",
        blurb: "One platform for CRM, marketing automation, funnels and follow-up, best for agencies and SMBs consolidating a stack of tools.",
        facts: [
          { label: "Role", value: "All-in-one platform" },
          { label: "Pricing", value: "From ~$97/mo, 14-day trial (verify)" },
          { label: "Best for", value: "Agencies & SMBs" },
        ],
        affiliateUrl: GOHIGHLEVEL_URL,
        reviewHref: "/gohighlevel",
        ctaLabel: "Try GoHighLevel",
      },
    ],
    faqs: [
      {
        q: "What are the best AI sales tools in 2026?",
        a: "It depends on the job. FullEnrich supplies verified contact data, Reply.io runs your own multichannel outreach, AiSDR is a done-for-you AI rep, and GoHighLevel is an all-in-one CRM and marketing platform. Many teams stack more than one.",
      },
      {
        q: "Which AI sales tool should I start with?",
        a: "Start with your bottleneck. Bad contact data points to FullEnrich; not enough conversations points to Reply.io or AiSDR; scattered tools and follow-up point to GoHighLevel. Pricing is indicative, verify current figures on each provider.",
      },
    ],
  },
  {
    slug: "research-peptides",
    eyebrow: "Category hub · Research use only",
    h1Lead: "Research peptide suppliers:",
    h1Accent: "purity and catalogue, compared",
    intro:
      "For laboratory research use only. This hub compares suppliers on testing documentation, catalogue depth and current offers, so researchers can source the right compound from a reputable vendor.",
    note: "All compounds referenced are for laboratory research purposes only and are not for human or veterinary use. Nothing here is medical advice.",
    metaTitle: "Research Peptide Suppliers Compared 2026: Purity & Catalogue | Refer Labs",
    metaDescription:
      "Compare research peptide suppliers for 2026 — Apollo Peptide Sciences, Ascension Peptides and BioPeptiTech, on third-party testing, catalogue depth and current offers. Research use only.",
    keywords: [
      "research peptide suppliers comparison",
      "best peptide supplier 2026",
      "compare peptide vendors",
      "apollo vs ascension peptides",
      "research peptides australia",
    ],
    roundupHref: { href: "/best-peptide-supplier", label: "Read the full supplier comparison" },
    relatedCategory: "Research peptides",
    providers: [
      {
        name: "Apollo Peptide Sciences",
        bestFor: "Broadest catalogue",
        blurb: "The widest research peptide catalogue of the three, with third-party testing documentation. A strong default when you need range. For research use only.",
        facts: [
          { label: "Catalogue", value: "Broadest" },
          { label: "Testing", value: "Third-party" },
          { label: "Offer", value: "Via referral link" },
        ],
        affiliateUrl: APOLLO_URL,
        reviewHref: "/apollopeptides",
        ctaLabel: "See Apollo",
        featured: true,
      },
      {
        name: "Ascension Peptides",
        bestFor: "Purity focus",
        blurb: "High-purity, lab-grade compounds frequently referenced in researcher communities for documentation quality. For research use only.",
        facts: [
          { label: "Focus", value: "High purity" },
          { label: "Testing", value: "Documented" },
          { label: "Offer", value: "Via referral link" },
        ],
        affiliateUrl: ASCENSION_URL,
        reviewHref: "/ascensionpeptides",
        ctaLabel: "See Ascension",
      },
      {
        name: "BioPeptiTech",
        bestFor: "Frequent sales",
        blurb: "Lab-grade compounds with regular promotions, a lower-cost entry point for longevity, metabolic and hormone-signalling research. For research use only.",
        facts: [
          { label: "Value", value: "Frequent sales" },
          { label: "Coverage", value: "Longevity, metabolic" },
          { label: "Offer", value: "Regular promotions" },
        ],
        affiliateUrl: BIOPEPTITECH_URL,
        reviewHref: "/biopeptitech",
        ctaLabel: "See BioPeptiTech",
      },
    ],
    faqs: [
      {
        q: "What is the best research peptide supplier in 2026?",
        a: "Apollo Peptide Sciences has the broadest catalogue, Ascension Peptides is cited for purity documentation, and BioPeptiTech runs frequent sales. The right choice depends on the compound and documentation you need. All products are for laboratory research use only.",
      },
      {
        q: "How do I get a research peptide discount?",
        a: "The most reliable route is an affiliate referral link, which applies any active offer automatically, rather than hunting for a promo code that may have expired. This hub links directly to each supplier. Research use only.",
      },
    ],
  },
];

export function getVertical(slug: string): Vertical | undefined {
  return CATALOG.find((v) => v.slug === slug);
}
